export const APPLICATION_URL = (
  organizationId = ':organizationId',
  projectId = ':projectId',
  environmentId = ':environmentId',
  applicationId = ':applicationId'
) => `/organization/${organizationId}/project/${projectId}/environment/${environmentId}/application/${applicationId}`
export const APPLICATION_GENERAL_URL = '/general'
export const APPLICATION_DEPLOYMENTS_URL = '/deployments'
export const APPLICATION_METRICS_URL = '/metrics'
export const APPLICATION_VARIABLES_URL = '/variables'
export const APPLICATION_SETTINGS_URL = '/settings'
