import { ExternalLink, truncateText } from '@qovery/shared/ui'
import type { SearchDocumentationResult } from '../hooks/use-mintlify-search/use-mintlify-search'

export interface MintlifyHitProps {
  result: SearchDocumentationResult
}

export function MintlifyHit({ result }: MintlifyHitProps) {
  const isApiResult = result.metadata?.autogeneratedByOpenApi === true

  const getTitle = () => {
    if (result.metadata?.title) {
      return result.metadata.title
    }
    const pathParts = result.path.split('/')
    const lastPart = pathParts[pathParts.length - 1] || pathParts[pathParts.length - 2]
    return lastPart
      ?.replace(/-/g, ' ')
      .split(' ')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ')
  }

  const getUrl = () => {
    if (result.path.startsWith('http')) {
      return result.path
    }
    return `https://qovery.com/docs${result.path.startsWith('/') ? '' : '/'}${result.path}`
  }

  const getDescription = () => {
    const maxLength = 150
    // For API results, prioritize metadata.description
    if (result.metadata?.description) {
      return result.metadata.description.length > maxLength
        ? `${truncateText(result.metadata.description, maxLength)}...`
        : result.metadata.description
    }
    // Fall back to content field
    if (result.content) {
      return result.content.length > maxLength ? `${truncateText(result.content, maxLength)}...` : result.content
    }
    return null
  }

  return (
    <ExternalLink href={getUrl()} withIcon={false}>
      <span className="flex flex-col gap-0.5">
        <span className="flex items-center gap-2">
          <span className="text-sm font-medium text-sky-500">{getTitle()}</span>
          {isApiResult && (
            <span className="rounded bg-purple-100 px-1.5 py-0.5 text-xs font-medium !text-purple-600 dark:bg-purple-500/20 dark:!text-purple-300">
              API
            </span>
          )}
        </span>
        {getDescription() && <span className="text-xs text-sky-400">{getDescription()}</span>}
      </span>
    </ExternalLink>
  )
}

export default MintlifyHit
