import { render, screen } from '@qovery/shared/util-tests'
import type { SearchDocumentationResult } from '../hooks/use-mintlify-search/use-mintlify-search'
import { MintlifyHit } from './mintlify-hit'

describe('MintlifyHit', () => {
  const mockResult: SearchDocumentationResult = {
    path: '/getting-started/introduction',
    metadata: {
      title: 'Introduction',
      description: 'Getting started with Qovery',
    },
  }

  it('should render the title from metadata', () => {
    render(<MintlifyHit result={mockResult} />)
    expect(screen.getByText('Introduction')).toBeTruthy()
  })

  it('should generate title from path when metadata title is missing', () => {
    const result = { ...mockResult, metadata: {} }
    render(<MintlifyHit result={result} />)
    expect(screen.getByText('Introduction')).toBeTruthy()
  })

  it('should display API badge for API results', () => {
    const result = {
      ...mockResult,
      metadata: { ...mockResult.metadata, autogeneratedByOpenApi: true },
    }
    render(<MintlifyHit result={result} />)
    expect(screen.getByText('API')).toBeTruthy()
  })

  it('should not display API badge for non-API results', () => {
    render(<MintlifyHit result={mockResult} />)
    expect(screen.queryByText('API')).toBeNull()
  })

  it('should display description when available', () => {
    render(<MintlifyHit result={mockResult} />)
    expect(screen.getByText('Getting started with Qovery')).toBeTruthy()
  })

  it('should truncate long descriptions', () => {
    const longDescription = 'a'.repeat(200)
    const result = {
      ...mockResult,
      metadata: { ...mockResult.metadata, description: longDescription },
    }
    const { container } = render(<MintlifyHit result={result} />)
    const descriptionElement = container.querySelector('.text-sky-400')
    expect(descriptionElement?.textContent?.length).toBeLessThan(200)
    expect(descriptionElement?.textContent).toMatch(/\.\.\./)
  })

  it('should generate correct URL for relative paths', () => {
    const { container } = render(<MintlifyHit result={mockResult} />)
    const link = container.querySelector('a')
    expect(link?.getAttribute('href')).toBe('https://qovery.com/docs/getting-started/introduction')
  })

  it('should use absolute URL when path starts with http', () => {
    const result = { ...mockResult, path: 'https://example.com/docs' }
    const { container } = render(<MintlifyHit result={result} />)
    const link = container.querySelector('a')
    expect(link?.getAttribute('href')).toBe('https://example.com/docs')
  })
})

