yarnPath: '.yarn/releases/yarn-berry.cjs'
nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: ${NPM_TOKEN}
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: ${NPM_TOKEN}
