export * from './lib/pages/onboarding-project-page/onboarding-project-page'
export * from './lib/pages/onboarding-pricing-page/onboarding-pricing-page'
export * from './lib/pages/onboarding-more-page/onboarding-more-page'
export * from './lib/pages/onboarding-company-page/onboarding-company-page'
export * from './lib/pages/onboarding-personalize-page/onboarding-personalize-page'
export * from './lib/onboarding-page'
