export const AUTH_PAGE_COPY = {
  shared: {
    backToWebsite: 'Back to website',
    logoAlt: 'Qovery logo black',
    legalPrefix: "By logging in or signing up, you agree to Qovery's",
    termsOfService: 'Terms of Service',
    legalAnd: 'and',
    privacyPolicy: 'Privacy Policy',
  },
  login: {
    title: 'Connect to your workspace',
    continueWithGoogle: 'Continue with Google',
    continueWithGithub: 'Continue with Github',
    continueWithSamlSso: 'Continue with SAML SSO',
    or: 'OR',
    lastUsed: 'Last used',
  },
  sso: {
    title: 'Enterprise single sign-on',
    description: 'Enter your company domain to connect with SSO',
    domainLabel: 'Company domain',
    domainPlaceholder: 'Enter your domain (e.g., company.com)',
    domainRequired: 'Please enter a domain.',
    domainInvalid: 'Invalid domain format',
    connect: 'Connect',
    changeLoginMethod: 'Change login method',
  },
  signUp: {
    title: 'Create your account',
    subtitle: 'Try Qovery free for 14 days, no credit card required.',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithGithub: 'Sign up with GitHub',
    or: 'or',
    signUpWithBitbucket: 'Sign up with Bitbucket',
    signUpWithGitlab: 'Sign up with GitLab',
    signUpWithMicrosoft: 'Sign up with Microsoft',
    logInPrompt: 'Already have an account?',
    logInLink: 'Log in',
    legalPrefix: 'By signing up, you agree to Qovery’s',
  },
} as const
