import { type ClusterMetricsDto, type ClusterStatusDto } from 'qovery-ws-typescript-axios'

// TODO: Need to be removed
export const fakeClusterMetrics: ClusterMetricsDto = {
  nodes: [
    {
      created_at: 1747200860000,
      name: 'ip-10-0-72-33.eu-west-3.compute.internal',
      architecture: 'amd64',
      instance_type: 't3.large',
      kernel_version: '5.10.236-227.928.amzn2.x86_64',
      kubelet_version: 'v1.31.7-eks-473151a',
      operating_system: 'linux',
      os_image: 'Amazon Linux 2',
      unschedulable: true,
      resources_allocatable: {
        cpu_milli: 1930,
        memory_mib: 7094,
        ephemeral_storage_mib: 16384,
        pods: 35,
      },
      resources_capacity: {
        cpu_milli: 2000,
        memory_mib: 7500,
        ephemeral_storage_mib: 19456,
        pods: 35,
      },
      resources_allocated: {
        request_cpu_milli: 100,
        limit_cpu_milli: null,
        request_memory_mib: 896,
        limit_memory_mib: null,
      },
      taints: [
        {
          key: 'nodepool/stable',
          value: '',
          effect: 'NoSchedule',
        },
        {
          key: 'node.kubernetes.io/unschedulable',
          value: '',
          effect: 'NoSchedule',
        },
        {
          key: 'karpenter.sh/disrupted',
          value: '',
          effect: 'NoSchedule',
        },
      ],
      conditions: [
        {
          type: 'MemoryPressure',
          status: 'False',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasSufficientMemory',
          message: 'kubelet has sufficient memory available',
        },
        {
          type: 'DiskPressure',
          status: 'False',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasNoDiskPressure',
          message: 'kubelet has no disk pressure',
        },
        {
          type: 'PIDPressure',
          status: 'False',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasSufficientPID',
          message: 'kubelet has sufficient PID available',
        },
        {
          type: 'Ready',
          status: 'True',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200876000,
          reason: 'KubeletReady',
          message: 'kubelet is posting ready status',
        },
      ],
      labels: {
        'beta.kubernetes.io/arch': 'amd64',
        'beta.kubernetes.io/instance-type': 't3.large',
        'beta.kubernetes.io/os': 'linux',
        'failure-domain.beta.kubernetes.io/region': 'eu-west-3',
        'failure-domain.beta.kubernetes.io/zone': 'eu-west-3c',
        'k8s.io/cloud-provider-aws': '9f568f9cccb434a574cda213bbc7f7f6',
        'karpenter.k8s.aws/instance-category': 't',
        'karpenter.k8s.aws/instance-cpu': '2',
        'karpenter.k8s.aws/instance-cpu-manufacturer': 'intel',
        'karpenter.k8s.aws/instance-ebs-bandwidth': '2780',
        'karpenter.k8s.aws/instance-encryption-in-transit-supported': 'false',
        'karpenter.k8s.aws/instance-family': 't3',
        'karpenter.k8s.aws/instance-generation': '3',
        'karpenter.k8s.aws/instance-hypervisor': 'nitro',
        'karpenter.k8s.aws/instance-memory': '8192',
        'karpenter.k8s.aws/instance-network-bandwidth': '512',
        'karpenter.k8s.aws/instance-size': 'large',
        'karpenter.sh/capacity-type': 'spot',
        'karpenter.sh/initialized': 'true',
        'karpenter.sh/nodepool': 'stable',
        'karpenter.sh/registered': 'true',
        'kubernetes.io/arch': 'amd64',
        'kubernetes.io/hostname': 'ip-10-0-72-33.eu-west-3.compute.internal',
        'kubernetes.io/os': 'linux',
        'node.kubernetes.io/exclude-from-external-load-balancers': 'karpenter',
        'node.kubernetes.io/instance-type': 't3.large',
        'topology.ebs.csi.aws.com/zone': 'eu-west-3c',
        'topology.k8s.aws/zone-id': 'euw3-az3',
        'topology.kubernetes.io/region': 'eu-west-3',
        'topology.kubernetes.io/zone': 'eu-west-3c',
      },
      annotations: {
        'alpha.kubernetes.io/provided-node-ip': '10.0.72.33',
        'compatibility.karpenter.k8s.aws/kubelet-drift-hash': '15379597991425564585',
        'csi.volume.kubernetes.io/nodeid': '{"ebs.csi.aws.com":"i-036a19a3f4983254c"}',
        'karpenter.k8s.aws/ec2nodeclass-hash': '12194261135232731854',
        'karpenter.k8s.aws/ec2nodeclass-hash-version': 'v3',
        'karpenter.sh/nodepool-hash': '13321557764212624671',
        'karpenter.sh/nodepool-hash-version': 'v3',
        'karpenter.sh/stored-version-migrated': 'true',
        'node.alpha.kubernetes.io/ttl': '0',
        'volumes.kubernetes.io/controller-managed-attach-detach': 'true',
      },
      addresses: [
        {
          type: 'InternalIP',
          address: '10.0.72.33',
        },
        {
          type: 'ExternalIP',
          address: '13.38.129.94',
        },
        {
          type: 'InternalDNS',
          address: 'ip-10-0-72-33.eu-west-3.compute.internal',
        },
        {
          type: 'Hostname',
          address: 'ip-10-0-72-33.eu-west-3.compute.internal',
        },
        {
          type: 'ExternalDNS',
          address: 'ec2-13-38-129-94.eu-west-3.compute.amazonaws.com',
        },
      ],
      pods: [
        {
          created_at: 1747200860000,
          name: 'aws-node-t8x77',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 2,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 44,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 70,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'aws-eks-nodeagent':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon/aws-network-policy-agent:v1.2.0-eksbuild.1',
            'aws-node': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon-k8s-cni:v1.19.3-eksbuild.1',
          },
          restart_count: 0,
        },
      ],
      metrics_usage: {
        cpu_milli_usage: 42,
        cpu_percent_usage: 2,
        memory_mib_rss_usage: 249,
        memory_percent_rss_usage: 3,
        memory_mib_working_set_usage: 628,
        memory_percent_working_set_usage: 8,
        disk_mib_usage: 211,
        disk_percent_usage: 1,
      },
    },
  ],
  pvcs: [],
  node_pools: [
    {
      name: 'default',
      nodes_count: 1,
      cpu_milli: 4000,
      memory_mib: 15614,
      cpu_milli_limit: null,
      memory_mib_limit: null,
    },
    {
      name: 'stable',
      nodes_count: 2,
      cpu_milli: 6000,
      memory_mib: 9702,
      cpu_milli_limit: null,
      memory_mib_limit: null,
    },
  ],
  tls_certificate: {
    dns_names: ['*.zc531a994.rustrocks.cloud'],
    not_before: 1745901462000,
    not_after: 1753677461000,
    renewal_time: 1751085461000,
    state: 'RUNNING',
    state_message: 'Certificate is up to date and has not expired',
    failed_issuance_attempt_count: 0,
    last_failure_issuance_time: null,
  },
}

export const fakeClusterRunningStatus: ClusterStatusDto = {
  computed_status: {
    global_status: 'WARNING',
    qovery_components_in_failure: [],
    qovery_components: [
      {
        name: 'karpenter',
        namespace: 'kube-system',
        status: 'RUNNING',
        error_detail: [],
        images_version: [
          'public.ecr.aws/karpenter/controller:1.0.9@sha256:80b2d0bf045ea5c02cc4abfc5f73cfea41dea772aa2e52c77bcadbaa27ed1ea0',
        ],
      },
      {
        name: 'cert-manager',
        namespace: 'cert-manager',
        status: 'RUNNING',
        error_detail: [],
        images_version: ['quay.io/jetstack/cert-manager-controller:v1.15.3'],
      },
    ],
    node_warnings: {
      'ip-10-0-94-96.eu-west-3.compute.internal': [
        {
          type: 'KubeletNotReady',
          reason: 'KubeletNotReady',
          message:
            'container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized',
          node_attributes: {
            node_pool_name: 'default',
          },
        },
      ],
    },
    is_max_nodes_size_reached: false,
    kube_version_status: {
      kube_version: '1.31',
      type: 'OK',
    },
  },
}
