const fakeData = {
  computed_status: {
    global_status: 'WARNING',
    qovery_components_in_failure: [],
    node_warnings: {
      'ip-10-0-94-96.eu-west-3.compute.internal': [
        {
          reason: 'KubeletNotReady',
          message:
            'container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized',
        },
      ],
    },
    is_max_nodes_size_reached: false,
    kube_version_status: {
      kube_version: '1.31',
      type: 'OK',
    },
  },
  nodes: [
    {
      created_at: 1747200860000,
      name: 'ip-10-0-72-33.eu-west-3.compute.internal',
      architecture: 'amd64',
      instance_type: 't3.large',
      kernel_version: '5.10.236-227.928.amzn2.x86_64',
      kubelet_version: 'v1.31.7-eks-473151a',
      operating_system: 'linux',
      os_image: 'Amazon Linux 2',
      unschedulable: true,
      resources_allocatable: {
        cpu_milli: 1930,
        memory_mib: 7094,
        ephemeral_storage_mib: 16384,
        pods: 35,
      },
      resources_allocated: {
        memory_mib: 896,
        cpu_milli: 100,
      },
      taints: [
        {
          key: 'nodepool/stable',
          value: '',
          effect: 'NoSchedule',
        },
        {
          key: 'node.kubernetes.io/unschedulable',
          value: '',
          effect: 'NoSchedule',
        },
        {
          key: 'karpenter.sh/disrupted',
          value: '',
          effect: 'NoSchedule',
        },
      ],
      conditions: [
        {
          type: 'MemoryPressure',
          status: 'False',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasSufficientMemory',
          message: 'kubelet has sufficient memory available',
        },
        {
          type: 'DiskPressure',
          status: 'False',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasNoDiskPressure',
          message: 'kubelet has no disk pressure',
        },
        {
          type: 'PIDPressure',
          status: 'False',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasSufficientPID',
          message: 'kubelet has sufficient PID available',
        },
        {
          type: 'Ready',
          status: 'True',
          last_heartbeat_time: 1747216613000,
          last_transition_time: 1747200876000,
          reason: 'KubeletReady',
          message: 'kubelet is posting ready status',
        },
      ],
      labels: {
        'beta.kubernetes.io/arch': 'amd64',
        'beta.kubernetes.io/instance-type': 't3.large',
        'beta.kubernetes.io/os': 'linux',
        'failure-domain.beta.kubernetes.io/region': 'eu-west-3',
        'failure-domain.beta.kubernetes.io/zone': 'eu-west-3c',
        'k8s.io/cloud-provider-aws': '9f568f9cccb434a574cda213bbc7f7f6',
        'karpenter.k8s.aws/instance-category': 't',
        'karpenter.k8s.aws/instance-cpu': '2',
        'karpenter.k8s.aws/instance-cpu-manufacturer': 'intel',
        'karpenter.k8s.aws/instance-ebs-bandwidth': '2780',
        'karpenter.k8s.aws/instance-encryption-in-transit-supported': 'false',
        'karpenter.k8s.aws/instance-family': 't3',
        'karpenter.k8s.aws/instance-generation': '3',
        'karpenter.k8s.aws/instance-hypervisor': 'nitro',
        'karpenter.k8s.aws/instance-memory': '8192',
        'karpenter.k8s.aws/instance-network-bandwidth': '512',
        'karpenter.k8s.aws/instance-size': 'large',
        'karpenter.sh/capacity-type': 'spot',
        'karpenter.sh/initialized': 'true',
        'karpenter.sh/nodepool': 'stable',
        'karpenter.sh/registered': 'true',
        'kubernetes.io/arch': 'amd64',
        'kubernetes.io/hostname': 'ip-10-0-72-33.eu-west-3.compute.internal',
        'kubernetes.io/os': 'linux',
        'node.kubernetes.io/exclude-from-external-load-balancers': 'karpenter',
        'node.kubernetes.io/instance-type': 't3.large',
        'topology.ebs.csi.aws.com/zone': 'eu-west-3c',
        'topology.k8s.aws/zone-id': 'euw3-az3',
        'topology.kubernetes.io/region': 'eu-west-3',
        'topology.kubernetes.io/zone': 'eu-west-3c',
      },
      annotations: {
        'alpha.kubernetes.io/provided-node-ip': '10.0.72.33',
        'compatibility.karpenter.k8s.aws/kubelet-drift-hash': '15379597991425564585',
        'csi.volume.kubernetes.io/nodeid': '{"ebs.csi.aws.com":"i-036a19a3f4983254c"}',
        'karpenter.k8s.aws/ec2nodeclass-hash': '12194261135232731854',
        'karpenter.k8s.aws/ec2nodeclass-hash-version': 'v3',
        'karpenter.sh/nodepool-hash': '13321557764212624671',
        'karpenter.sh/nodepool-hash-version': 'v3',
        'karpenter.sh/stored-version-migrated': 'true',
        'node.alpha.kubernetes.io/ttl': '0',
        'volumes.kubernetes.io/controller-managed-attach-detach': 'true',
      },
      addresses: [
        {
          type: 'InternalIP',
          address: '10.0.72.33',
        },
        {
          type: 'ExternalIP',
          address: '13.38.129.94',
        },
        {
          type: 'InternalDNS',
          address: 'ip-10-0-72-33.eu-west-3.compute.internal',
        },
        {
          type: 'Hostname',
          address: 'ip-10-0-72-33.eu-west-3.compute.internal',
        },
        {
          type: 'ExternalDNS',
          address: 'ec2-13-38-129-94.eu-west-3.compute.amazonaws.com',
        },
      ],
      pods: [
        {
          created_at: 1747200860000,
          name: 'aws-node-t8x77',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 2,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 44,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 70,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'aws-eks-nodeagent':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon/aws-network-policy-agent:v1.2.0-eksbuild.1',
            'aws-node': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon-k8s-cni:v1.19.3-eksbuild.1',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200860000,
          name: 'ebs-csi-node-ljwmh',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 30,
          cpu_milli_limit: null,
          memory_mib_request: 120,
          memory_mib_limit: 768,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 18,
            memory_percent_rss_usage: 2,
            memory_mib_working_set_usage: 19,
            memory_percent_working_set_usage: 2,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'ebs-plugin': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/aws-ebs-csi-driver:v1.40.0',
            'liveness-probe': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/livenessprobe:v2.14.0-eks-1-32-6',
            'node-driver-registrar':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-node-driver-registrar:v2.13.0-eks-1-32-6',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200860000,
          name: 'kube-proxy-lw8dv',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 14,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 15,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 1,
            disk_percent_usage: 0,
          },
          images_version: {
            'kube-proxy': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/kube-proxy:v1.31.3-minimal-eksbuild.2',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200860000,
          name: 'promtail-4ksfw',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 100,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: 7,
            cpu_percent_usage: 7,
            memory_mib_rss_usage: 21,
            memory_percent_rss_usage: 16,
            memory_mib_working_set_usage: 24,
            memory_percent_working_set_usage: 18,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            promtail: 'public.ecr.aws/r3m4q3r9/pub-mirror-promtail:3.0.0',
          },
          restart_count: 0,
        },
      ],
      metrics_usage: {
        cpu_milli_usage: 42,
        cpu_percent_usage: 2,
        memory_mib_rss_usage: 249,
        memory_percent_rss_usage: 3,
        memory_mib_working_set_usage: 628,
        memory_percent_working_set_usage: 8,
        disk_mib_usage: 211,
        disk_percent_usage: 1,
      },
    },
    {
      created_at: 1747216615000,
      name: 'ip-10-0-94-96.eu-west-3.compute.internal',
      architecture: 'amd64',
      instance_type: 't3.small',
      kernel_version: '5.10.236-227.928.amzn2.x86_64',
      kubelet_version: 'v1.31.7-eks-473151a',
      operating_system: 'linux',
      os_image: 'Amazon Linux 2',
      unschedulable: false,
      resources_allocatable: {
        cpu_milli: 1930,
        memory_mib: 1448,
        ephemeral_storage_mib: 16384,
        pods: 11,
      },
      resources_allocated: {
        memory_mib: 896,
        cpu_milli: 100,
      },
      taints: [
        {
          key: 'nodepool/stable',
          value: '',
          effect: 'NoSchedule',
        },
        {
          key: 'node.kubernetes.io/not-ready',
          value: '',
          effect: 'NoSchedule',
        },
        {
          key: 'node.kubernetes.io/not-ready',
          value: '',
          effect: 'NoExecute',
        },
      ],
      conditions: [
        {
          type: 'MemoryPressure',
          status: 'False',
          last_heartbeat_time: 1747216625000,
          last_transition_time: 1747216615000,
          reason: 'KubeletHasSufficientMemory',
          message: 'kubelet has sufficient memory available',
        },
        {
          type: 'DiskPressure',
          status: 'False',
          last_heartbeat_time: 1747216625000,
          last_transition_time: 1747216615000,
          reason: 'KubeletHasNoDiskPressure',
          message: 'kubelet has no disk pressure',
        },
        {
          type: 'PIDPressure',
          status: 'False',
          last_heartbeat_time: 1747216625000,
          last_transition_time: 1747216615000,
          reason: 'KubeletHasSufficientPID',
          message: 'kubelet has sufficient PID available',
        },
        {
          type: 'Ready',
          status: 'False',
          last_heartbeat_time: 1747216625000,
          last_transition_time: 1747216615000,
          reason: 'KubeletNotReady',
          message:
            'container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized',
        },
      ],
      labels: {
        'beta.kubernetes.io/arch': 'amd64',
        'beta.kubernetes.io/instance-type': 't3.small',
        'beta.kubernetes.io/os': 'linux',
        'failure-domain.beta.kubernetes.io/region': 'eu-west-3',
        'failure-domain.beta.kubernetes.io/zone': 'eu-west-3c',
        'k8s.io/cloud-provider-aws': '9f568f9cccb434a574cda213bbc7f7f6',
        'karpenter.k8s.aws/instance-category': 't',
        'karpenter.k8s.aws/instance-cpu': '2',
        'karpenter.k8s.aws/instance-cpu-manufacturer': 'intel',
        'karpenter.k8s.aws/instance-ebs-bandwidth': '2085',
        'karpenter.k8s.aws/instance-encryption-in-transit-supported': 'false',
        'karpenter.k8s.aws/instance-family': 't3',
        'karpenter.k8s.aws/instance-generation': '3',
        'karpenter.k8s.aws/instance-hypervisor': 'nitro',
        'karpenter.k8s.aws/instance-memory': '2048',
        'karpenter.k8s.aws/instance-network-bandwidth': '128',
        'karpenter.k8s.aws/instance-size': 'small',
        'karpenter.sh/capacity-type': 'spot',
        'karpenter.sh/nodepool': 'stable',
        'karpenter.sh/registered': 'true',
        'kubernetes.io/arch': 'amd64',
        'kubernetes.io/hostname': 'ip-10-0-94-96.eu-west-3.compute.internal',
        'kubernetes.io/os': 'linux',
        'node.kubernetes.io/instance-type': 't3.small',
        'topology.k8s.aws/zone-id': 'euw3-az3',
        'topology.kubernetes.io/region': 'eu-west-3',
        'topology.kubernetes.io/zone': 'eu-west-3c',
      },
      annotations: {
        'alpha.kubernetes.io/provided-node-ip': '10.0.94.96',
        'compatibility.karpenter.k8s.aws/kubelet-drift-hash': '15379597991425564585',
        'karpenter.k8s.aws/ec2nodeclass-hash': '12194261135232731854',
        'karpenter.k8s.aws/ec2nodeclass-hash-version': 'v3',
        'karpenter.sh/nodepool-hash': '13321557764212624671',
        'karpenter.sh/nodepool-hash-version': 'v3',
        'karpenter.sh/stored-version-migrated': 'true',
        'node.alpha.kubernetes.io/ttl': '0',
        'volumes.kubernetes.io/controller-managed-attach-detach': 'true',
      },
      addresses: [
        {
          type: 'InternalIP',
          address: '10.0.94.96',
        },
        {
          type: 'ExternalIP',
          address: '13.39.16.104',
        },
        {
          type: 'InternalDNS',
          address: 'ip-10-0-94-96.eu-west-3.compute.internal',
        },
        {
          type: 'Hostname',
          address: 'ip-10-0-94-96.eu-west-3.compute.internal',
        },
        {
          type: 'ExternalDNS',
          address: 'ec2-13-39-16-104.eu-west-3.compute.amazonaws.com',
        },
      ],
      pods: [
        {
          created_at: 1747216615000,
          name: 'aws-node-h6p2k',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'aws-eks-nodeagent':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon/aws-network-policy-agent:v1.2.0-eksbuild.1',
            'aws-node': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon-k8s-cni:v1.19.3-eksbuild.1',
          },
          restart_count: 0,
        },
        {
          created_at: 1747216615000,
          name: 'ebs-csi-node-nxb9w',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 30,
          cpu_milli_limit: null,
          memory_mib_request: 120,
          memory_mib_limit: 768,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'ebs-plugin': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/aws-ebs-csi-driver:v1.40.0',
            'liveness-probe': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/livenessprobe:v2.14.0-eks-1-32-6',
            'node-driver-registrar':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-node-driver-registrar:v2.13.0-eks-1-32-6',
          },
          restart_count: 0,
        },
        {
          created_at: 1747216615000,
          name: 'kube-proxy-4lxs9',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'kube-proxy': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/kube-proxy:v1.31.3-minimal-eksbuild.2',
          },
          restart_count: 0,
        },
        {
          created_at: 1747216615000,
          name: 'promtail-jwtnl',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 100,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            promtail: 'public.ecr.aws/r3m4q3r9/pub-mirror-promtail:3.0.0',
          },
          restart_count: 0,
        },
      ],
      metrics_usage: {
        cpu_milli_usage: null,
        cpu_percent_usage: 0,
        memory_mib_rss_usage: null,
        memory_percent_rss_usage: 0,
        memory_mib_working_set_usage: null,
        memory_percent_working_set_usage: 0,
        disk_mib_usage: null,
        disk_percent_usage: 0,
      },
    },
    {
      created_at: 1747200810000,
      name: 'fargate-ip-10-0-166-154.eu-west-3.compute.internal',
      architecture: 'amd64',
      instance_type: null,
      kernel_version: '5.10.235-227.919.amzn2.x86_64',
      kubelet_version: 'v1.31.4-eks-2d5f260',
      operating_system: 'linux',
      os_image: 'Amazon Linux 2',
      unschedulable: false,
      resources_allocatable: {
        cpu_milli: 2000,
        memory_mib: 3750,
        ephemeral_storage_mib: 16384,
        pods: 1,
      },
      resources_allocated: {
        memory_mib: 1024,
        cpu_milli: 1000,
      },
      taints: [
        {
          key: 'eks.amazonaws.com/compute-type',
          value: 'fargate',
          effect: 'NoSchedule',
        },
      ],
      conditions: [
        {
          type: 'MemoryPressure',
          status: 'False',
          last_heartbeat_time: 1747216455000,
          last_transition_time: 1747200810000,
          reason: 'KubeletHasSufficientMemory',
          message: 'kubelet has sufficient memory available',
        },
        {
          type: 'DiskPressure',
          status: 'False',
          last_heartbeat_time: 1747216455000,
          last_transition_time: 1747200810000,
          reason: 'KubeletHasNoDiskPressure',
          message: 'kubelet has no disk pressure',
        },
        {
          type: 'PIDPressure',
          status: 'False',
          last_heartbeat_time: 1747216455000,
          last_transition_time: 1747200810000,
          reason: 'KubeletHasSufficientPID',
          message: 'kubelet has sufficient PID available',
        },
        {
          type: 'Ready',
          status: 'True',
          last_heartbeat_time: 1747216455000,
          last_transition_time: 1747200810000,
          reason: 'KubeletReady',
          message: 'kubelet is posting ready status',
        },
      ],
      labels: {
        'beta.kubernetes.io/arch': 'amd64',
        'beta.kubernetes.io/os': 'linux',
        'eks.amazonaws.com/compute-type': 'fargate',
        'failure-domain.beta.kubernetes.io/region': 'eu-west-3',
        'failure-domain.beta.kubernetes.io/zone': 'eu-west-3a',
        'kubernetes.io/arch': 'amd64',
        'kubernetes.io/hostname': 'fargate-ip-10-0-166-154.eu-west-3.compute.internal',
        'kubernetes.io/os': 'linux',
        'topology.k8s.aws/zone-id': 'euw3-az1',
        'topology.kubernetes.io/region': 'eu-west-3',
        'topology.kubernetes.io/zone': 'eu-west-3a',
      },
      annotations: {
        'node.alpha.kubernetes.io/ttl': '0',
        'volumes.kubernetes.io/controller-managed-attach-detach': 'true',
      },
      addresses: [
        {
          type: 'InternalIP',
          address: '10.0.166.154',
        },
        {
          type: 'InternalDNS',
          address: 'ip-10-0-166-154.eu-west-3.compute.internal',
        },
        {
          type: 'Hostname',
          address: 'fargate-ip-10-0-166-154.eu-west-3.compute.internal',
        },
      ],
      pods: [
        {
          created_at: 1747200765000,
          name: 'karpenter-6c865f5875-cvcdx',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 1000,
          cpu_milli_limit: 1000,
          memory_mib_request: 1024,
          memory_mib_limit: 1024,
          metrics_usage: {
            cpu_milli_usage: 2,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 74,
            memory_percent_rss_usage: 7,
            memory_mib_working_set_usage: 76,
            memory_percent_working_set_usage: 7,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            controller:
              'public.ecr.aws/karpenter/controller:1.0.9@sha256:80b2d0bf045ea5c02cc4abfc5f73cfea41dea772aa2e52c77bcadbaa27ed1ea0',
          },
          restart_count: 0,
        },
      ],
      metrics_usage: {
        cpu_milli_usage: 18,
        cpu_percent_usage: 0,
        memory_mib_rss_usage: 165,
        memory_percent_rss_usage: 4,
        memory_mib_working_set_usage: 192,
        memory_percent_working_set_usage: 5,
        disk_mib_usage: 3636,
        disk_percent_usage: 22,
      },
    },
    {
      created_at: 1747200861000,
      name: 'ip-10-0-13-174.eu-west-3.compute.internal',
      architecture: 'arm64',
      instance_type: 'm6gd.xlarge',
      kernel_version: '5.10.236-227.928.amzn2.aarch64',
      kubelet_version: 'v1.31.7-eks-473151a',
      operating_system: 'linux',
      os_image: 'Amazon Linux 2',
      unschedulable: false,
      resources_allocatable: {
        cpu_milli: 3920,
        memory_mib: 14621,
        ephemeral_storage_mib: 16384,
        pods: 58,
      },
      resources_allocated: {
        memory_mib: 7116,
        cpu_milli: 6695,
      },
      taints: [],
      conditions: [
        {
          type: 'MemoryPressure',
          status: 'False',
          last_heartbeat_time: 1747216447000,
          last_transition_time: 1747200861000,
          reason: 'KubeletHasSufficientMemory',
          message: 'kubelet has sufficient memory available',
        },
        {
          type: 'DiskPressure',
          status: 'False',
          last_heartbeat_time: 1747216447000,
          last_transition_time: 1747200861000,
          reason: 'KubeletHasNoDiskPressure',
          message: 'kubelet has no disk pressure',
        },
        {
          type: 'PIDPressure',
          status: 'False',
          last_heartbeat_time: 1747216447000,
          last_transition_time: 1747200861000,
          reason: 'KubeletHasSufficientPID',
          message: 'kubelet has sufficient PID available',
        },
        {
          type: 'Ready',
          status: 'True',
          last_heartbeat_time: 1747216447000,
          last_transition_time: 1747200874000,
          reason: 'KubeletReady',
          message: 'kubelet is posting ready status',
        },
      ],
      labels: {
        'beta.kubernetes.io/arch': 'arm64',
        'beta.kubernetes.io/instance-type': 'm6gd.xlarge',
        'beta.kubernetes.io/os': 'linux',
        'eks.amazonaws.com/compute-type': '7925099551958576845',
        'failure-domain.beta.kubernetes.io/region': 'eu-west-3',
        'failure-domain.beta.kubernetes.io/zone': 'eu-west-3a',
        'k8s.io/cloud-provider-aws': '9f568f9cccb434a574cda213bbc7f7f6',
        'karpenter.k8s.aws/instance-category': 'm',
        'karpenter.k8s.aws/instance-cpu': '4',
        'karpenter.k8s.aws/instance-cpu-manufacturer': 'aws',
        'karpenter.k8s.aws/instance-ebs-bandwidth': '4750',
        'karpenter.k8s.aws/instance-encryption-in-transit-supported': 'false',
        'karpenter.k8s.aws/instance-family': 'm6gd',
        'karpenter.k8s.aws/instance-generation': '6',
        'karpenter.k8s.aws/instance-hypervisor': 'nitro',
        'karpenter.k8s.aws/instance-local-nvme': '237',
        'karpenter.k8s.aws/instance-memory': '16384',
        'karpenter.k8s.aws/instance-network-bandwidth': '1250',
        'karpenter.k8s.aws/instance-size': 'xlarge',
        'karpenter.sh/capacity-type': 'spot',
        'karpenter.sh/initialized': 'true',
        'karpenter.sh/nodepool': 'default',
        'karpenter.sh/registered': 'true',
        'kubernetes.io/arch': 'arm64',
        'kubernetes.io/hostname': 'ip-10-0-13-174.eu-west-3.compute.internal',
        'kubernetes.io/os': 'linux',
        'node.kubernetes.io/instance-type': 'm6gd.xlarge',
        'topology.ebs.csi.aws.com/zone': 'eu-west-3a',
        'topology.k8s.aws/zone-id': 'euw3-az1',
        'topology.kubernetes.io/region': 'eu-west-3',
        'topology.kubernetes.io/zone': 'eu-west-3a',
      },
      annotations: {
        'alpha.kubernetes.io/provided-node-ip': '10.0.13.174',
        'compatibility.karpenter.k8s.aws/kubelet-drift-hash': '15379597991425564585',
        'csi.volume.kubernetes.io/nodeid': '{"ebs.csi.aws.com":"i-055e2d49d814ff3b5"}',
        'karpenter.k8s.aws/ec2nodeclass-hash': '12194261135232731854',
        'karpenter.k8s.aws/ec2nodeclass-hash-version': 'v3',
        'karpenter.sh/nodepool-hash': '15015733878877233177',
        'karpenter.sh/nodepool-hash-version': 'v3',
        'karpenter.sh/stored-version-migrated': 'true',
        'node.alpha.kubernetes.io/ttl': '0',
        'volumes.kubernetes.io/controller-managed-attach-detach': 'true',
      },
      addresses: [
        {
          type: 'InternalIP',
          address: '10.0.13.174',
        },
        {
          type: 'ExternalIP',
          address: '51.44.181.68',
        },
        {
          type: 'InternalDNS',
          address: 'ip-10-0-13-174.eu-west-3.compute.internal',
        },
        {
          type: 'Hostname',
          address: 'ip-10-0-13-174.eu-west-3.compute.internal',
        },
        {
          type: 'ExternalDNS',
          address: 'ec2-51-44-181-68.eu-west-3.compute.amazonaws.com',
        },
      ],
      pods: [
        {
          created_at: 1747159286000,
          name: 'cert-manager-6cd657bf55-xhsbw',
          namespace: 'cert-manager',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 200,
          memory_mib_request: 192,
          memory_mib_limit: 192,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 23,
            memory_percent_rss_usage: 11,
            memory_mib_working_set_usage: 24,
            memory_percent_working_set_usage: 12,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'cert-manager-controller': 'quay.io/jetstack/cert-manager-controller:v1.15.3',
          },
          restart_count: 0,
        },
        {
          created_at: 1747201071000,
          name: 'cert-manager-cainjector-d88c9d475-bb78g',
          namespace: 'cert-manager',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 500,
          memory_mib_request: 334,
          memory_mib_limit: 334,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 109,
            memory_percent_rss_usage: 32,
            memory_mib_working_set_usage: 111,
            memory_percent_working_set_usage: 33,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'cert-manager-cainjector': 'quay.io/jetstack/cert-manager-cainjector:v1.15.3',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159289000,
          name: 'cert-manager-webhook-6fcb9cf8d5-rvzvr',
          namespace: 'cert-manager',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: 200,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 9,
            memory_percent_rss_usage: 7,
            memory_mib_working_set_usage: 9,
            memory_percent_working_set_usage: 7,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'cert-manager-webhook': 'quay.io/jetstack/cert-manager-webhook:v1.15.3',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200941000,
          name: 'qovery-cert-manager-webhook-7cb85d46d8-rgqc2',
          namespace: 'cert-manager',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 64,
          memory_mib_limit: 64,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: 2,
            memory_mib_rss_usage: 25,
            memory_percent_rss_usage: 39,
            memory_mib_working_set_usage: 26,
            memory_percent_working_set_usage: 40,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'qovery-cert-manager-webhook': 'public.ecr.aws/r3m4q3r9/cert-manager-webhook-qovery:f49b03d8',
          },
          restart_count: 2,
        },
        {
          created_at: 1747200861000,
          name: 'aws-node-9fc8p',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 2,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 98,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 125,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'aws-eks-nodeagent':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon/aws-network-policy-agent:v1.2.0-eksbuild.1',
            'aws-node': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon-k8s-cni:v1.19.3-eksbuild.1',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159397000,
          name: 'coredns-845d44b5d8-kbgsd',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: null,
          memory_mib_request: 70,
          memory_mib_limit: 170,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 19,
            memory_percent_rss_usage: 11,
            memory_mib_working_set_usage: 21,
            memory_percent_working_set_usage: 12,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            coredns: '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/coredns:v1.11.4-eksbuild.2',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159289000,
          name: 'coredns-845d44b5d8-rz6zw',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: null,
          memory_mib_request: 70,
          memory_mib_limit: 170,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 19,
            memory_percent_rss_usage: 11,
            memory_mib_working_set_usage: 20,
            memory_percent_working_set_usage: 11,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            coredns: '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/coredns:v1.11.4-eksbuild.2',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159290000,
          name: 'ebs-csi-controller-767665479f-mfptz',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 60,
          cpu_milli_limit: null,
          memory_mib_request: 240,
          memory_mib_limit: 1536,
          metrics_usage: {
            cpu_milli_usage: 2,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 55,
            memory_percent_rss_usage: 3,
            memory_mib_working_set_usage: 59,
            memory_percent_working_set_usage: 3,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'csi-attacher': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-attacher:v4.8.0-eks-1-32-6',
            'csi-provisioner': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-provisioner:v5.2.0-eks-1-32-6',
            'csi-resizer': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-resizer:v1.13.1-eks-1-32-6',
            'csi-snapshotter': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-snapshotter:v8.2.0-eks-1-32-6',
            'ebs-plugin': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/aws-ebs-csi-driver:v1.40.0',
            'liveness-probe': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/livenessprobe:v2.14.0-eks-1-32-6',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159397000,
          name: 'ebs-csi-controller-767665479f-sjfmt',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 60,
          cpu_milli_limit: null,
          memory_mib_request: 240,
          memory_mib_limit: 1536,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 50,
            memory_percent_rss_usage: 3,
            memory_mib_working_set_usage: 54,
            memory_percent_working_set_usage: 3,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'csi-attacher': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-attacher:v4.8.0-eks-1-32-6',
            'csi-provisioner': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-provisioner:v5.2.0-eks-1-32-6',
            'csi-resizer': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-resizer:v1.13.1-eks-1-32-6',
            'csi-snapshotter': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-snapshotter:v8.2.0-eks-1-32-6',
            'ebs-plugin': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/aws-ebs-csi-driver:v1.40.0',
            'liveness-probe': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/livenessprobe:v2.14.0-eks-1-32-6',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200861000,
          name: 'ebs-csi-node-hnz97',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 30,
          cpu_milli_limit: null,
          memory_mib_request: 120,
          memory_mib_limit: 768,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 19,
            memory_percent_rss_usage: 2,
            memory_mib_working_set_usage: 21,
            memory_percent_working_set_usage: 2,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'ebs-plugin': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/aws-ebs-csi-driver:v1.40.0',
            'liveness-probe': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/livenessprobe:v2.14.0-eks-1-32-6',
            'node-driver-registrar':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-node-driver-registrar:v2.13.0-eks-1-32-6',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159287000,
          name: 'externaldns-external-dns-6f9cb66bbd-gc7ll',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 50,
          memory_mib_limit: 50,
          metrics_usage: {
            cpu_milli_usage: 2,
            cpu_percent_usage: 4,
            memory_mib_rss_usage: 24,
            memory_percent_rss_usage: 48,
            memory_mib_working_set_usage: 26,
            memory_percent_working_set_usage: 52,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'external-dns': 'public.ecr.aws/r3m4q3r9/pub-mirror-externaldns:0.15.0-debian-12-r1',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159287000,
          name: 'iam-eks-user-mapper-76895c5456-fvmfp',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 10,
          cpu_milli_limit: 20,
          memory_mib_request: 32,
          memory_mib_limit: 32,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 2,
            memory_percent_rss_usage: 6,
            memory_mib_working_set_usage: 2,
            memory_percent_working_set_usage: 6,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'iam-eks-user-mapper': 'public.ecr.aws/r3m4q3r9/iam-eks-user-mapper-rs:861f577b',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200861000,
          name: 'kube-proxy-mkbw4',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 14,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 15,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 1,
            disk_percent_usage: 0,
          },
          images_version: {
            'kube-proxy': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/kube-proxy:v1.31.3-minimal-eksbuild.2',
          },
          restart_count: 0,
        },
        {
          created_at: 1747201071000,
          name: 'metrics-server-7946d645c6-zkmgq',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 250,
          cpu_milli_limit: 250,
          memory_mib_request: 64,
          memory_mib_limit: 64,
          metrics_usage: {
            cpu_milli_usage: 5,
            cpu_percent_usage: 2,
            memory_mib_rss_usage: 29,
            memory_percent_rss_usage: 45,
            memory_mib_working_set_usage: 30,
            memory_percent_working_set_usage: 46,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'metrics-server': 'registry.k8s.io/metrics-server/metrics-server:v0.7.1',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200861000,
          name: 'promtail-j69q9',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 100,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: 6,
            cpu_percent_usage: 6,
            memory_mib_rss_usage: 43,
            memory_percent_rss_usage: 33,
            memory_mib_working_set_usage: 46,
            memory_percent_working_set_usage: 35,
            disk_mib_usage: 2,
            disk_percent_usage: 0,
          },
          images_version: {
            promtail: 'public.ecr.aws/r3m4q3r9/pub-mirror-promtail:3.0.0',
          },
          restart_count: 0,
        },
        {
          created_at: 1747216621000,
          name: 'vertical-pod-autoscaler-vpa-admission-controller-7877548b8jh92p',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 1000,
          memory_mib_request: 500,
          memory_mib_limit: 500,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 0,
            memory_percent_rss_usage: 0,
            memory_mib_working_set_usage: 0,
            memory_percent_working_set_usage: 0,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            vpa: 'registry.k8s.io/autoscaling/vpa-admission-controller:1.0.0',
          },
          restart_count: 0,
        },
        {
          created_at: 1747201006000,
          name: 'vertical-pod-autoscaler-vpa-recommender-f85c796b8-4jjmz',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 1000,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: 3,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 23,
            memory_percent_rss_usage: 17,
            memory_mib_working_set_usage: 24,
            memory_percent_working_set_usage: 18,
            disk_mib_usage: 2,
            disk_percent_usage: 0,
          },
          images_version: {
            vpa: 'registry.k8s.io/autoscaling/vpa-recommender:1.0.0',
          },
          restart_count: 0,
        },
        {
          created_at: 1747201198000,
          name: 'vertical-pod-autoscaler-vpa-updater-5f6d8fcc-grp8j',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 1000,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 27,
            memory_percent_rss_usage: 21,
            memory_mib_working_set_usage: 28,
            memory_percent_working_set_usage: 21,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            vpa: 'registry.k8s.io/autoscaling/vpa-updater:1.0.0',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159289000,
          name: 'grafana-7d9c54c7d-56k9c',
          namespace: 'prometheus',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 0,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 34,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 37,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 1,
            disk_percent_usage: 0,
          },
          images_version: {
            grafana: 'grafana/grafana:8.1.5',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159288000,
          name: 'k8s-event-logger-86559fd67-sdgd9',
          namespace: 'qovery',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: 500,
          memory_mib_request: 32,
          memory_mib_limit: 384,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 7,
            memory_percent_rss_usage: 1,
            memory_mib_working_set_usage: 8,
            memory_percent_working_set_usage: 2,
            disk_mib_usage: 3,
            disk_percent_usage: 0,
          },
          images_version: {
            'k8s-event-logger': 'public.ecr.aws/r3m4q3r9/pub-mirror-k8s-event-logger:2.1',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159287000,
          name: 'qovery-cluster-agent-869f7fbcf4-m8745',
          namespace: 'qovery',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 150,
          cpu_milli_limit: 750,
          memory_mib_request: 64,
          memory_mib_limit: 320,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 7,
            memory_percent_rss_usage: 2,
            memory_mib_working_set_usage: 8,
            memory_percent_working_set_usage: 2,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'qovery-cluster-agent': 'public.ecr.aws/r3m4q3r9/cluster-agent:1cc4eae0685d2c2f0d878269c820f1752f5719a5',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159288000,
          name: 'shell-agent-qovery-shell-agent-68ff868fc-2vt9d',
          namespace: 'qovery',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 200,
          cpu_milli_limit: 1000,
          memory_mib_request: 100,
          memory_mib_limit: 100,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 2,
            memory_percent_rss_usage: 2,
            memory_mib_working_set_usage: 3,
            memory_percent_working_set_usage: 3,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'qovery-shell-agent': 'public.ecr.aws/r3m4q3r9/shell-agent:bbc5f528e21cc69848eebf3e08e8644979a23742',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159288000,
          name: 'helm-z96a099e3-kubeprometh-operator-798cc655df-92sbr',
          namespace: 'zee52471d-newkubeprometheusstack',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 0,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 21,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 22,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'kube-prometheus-stack': 'quay.io/prometheus-operator/prometheus-operator:v0.79.2',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159287000,
          name: 'helm-z96a099e3-kubeprometheustackchart-kube-state-metrics-zz7q4',
          namespace: 'zee52471d-newkubeprometheusstack',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 75,
          cpu_milli_limit: 75,
          memory_mib_request: 384,
          memory_mib_limit: 384,
          metrics_usage: {
            cpu_milli_usage: 3,
            cpu_percent_usage: 4,
            memory_mib_rss_usage: 26,
            memory_percent_rss_usage: 6,
            memory_mib_working_set_usage: 28,
            memory_percent_working_set_usage: 7,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'kube-state-metrics': 'registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.14.0',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159289000,
          name: 'prometheus-helm-z96a099e3-kubeprometh-prometheus-0',
          namespace: 'zee52471d-newkubeprometheusstack',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 500,
          cpu_milli_limit: null,
          memory_mib_request: 1024,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 10,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 750,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 763,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 584,
            disk_percent_usage: 3,
          },
          images_version: {
            'config-reloader': 'quay.io/prometheus-operator/prometheus-config-reloader:v0.79.2',
            prometheus: 'quay.io/prometheus/prometheus:v3.0.1',
          },
          restart_count: 0,
        },
      ],
      metrics_usage: {
        cpu_milli_usage: 117,
        cpu_percent_usage: 2,
        memory_mib_rss_usage: 1755,
        memory_percent_rss_usage: 12,
        memory_mib_working_set_usage: 2306,
        memory_percent_working_set_usage: 15,
        disk_mib_usage: 2719,
        disk_percent_usage: 16,
      },
    },
    {
      created_at: 1747200861000,
      name: 'ip-10-0-27-85.eu-west-3.compute.internal',
      architecture: 'amd64',
      instance_type: 'c7i-flex.xlarge',
      kernel_version: '5.10.236-227.928.amzn2.x86_64',
      kubelet_version: 'v1.31.7-eks-473151a',
      operating_system: 'linux',
      os_image: 'Amazon Linux 2',
      unschedulable: false,
      resources_allocatable: {
        cpu_milli: 3920,
        memory_mib: 6785,
        ephemeral_storage_mib: 16384,
        pods: 58,
      },
      resources_allocated: {
        memory_mib: 5498,
        cpu_milli: 3714,
      },
      taints: [
        {
          key: 'nodepool/stable',
          value: '',
          effect: 'NoSchedule',
        },
      ],
      conditions: [
        {
          type: 'MemoryPressure',
          status: 'False',
          last_heartbeat_time: 1747216616000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasSufficientMemory',
          message: 'kubelet has sufficient memory available',
        },
        {
          type: 'DiskPressure',
          status: 'False',
          last_heartbeat_time: 1747216616000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasNoDiskPressure',
          message: 'kubelet has no disk pressure',
        },
        {
          type: 'PIDPressure',
          status: 'False',
          last_heartbeat_time: 1747216616000,
          last_transition_time: 1747200860000,
          reason: 'KubeletHasSufficientPID',
          message: 'kubelet has sufficient PID available',
        },
        {
          type: 'Ready',
          status: 'True',
          last_heartbeat_time: 1747216616000,
          last_transition_time: 1747200873000,
          reason: 'KubeletReady',
          message: 'kubelet is posting ready status',
        },
      ],
      labels: {
        'beta.kubernetes.io/arch': 'amd64',
        'beta.kubernetes.io/instance-type': 'c7i-flex.xlarge',
        'beta.kubernetes.io/os': 'linux',
        'failure-domain.beta.kubernetes.io/region': 'eu-west-3',
        'failure-domain.beta.kubernetes.io/zone': 'eu-west-3a',
        'k8s.io/cloud-provider-aws': '9f568f9cccb434a574cda213bbc7f7f6',
        'karpenter.k8s.aws/instance-category': 'c',
        'karpenter.k8s.aws/instance-cpu': '4',
        'karpenter.k8s.aws/instance-cpu-manufacturer': 'intel',
        'karpenter.k8s.aws/instance-ebs-bandwidth': '10000',
        'karpenter.k8s.aws/instance-encryption-in-transit-supported': 'true',
        'karpenter.k8s.aws/instance-family': 'c7i-flex',
        'karpenter.k8s.aws/instance-generation': '7',
        'karpenter.k8s.aws/instance-hypervisor': 'nitro',
        'karpenter.k8s.aws/instance-memory': '8192',
        'karpenter.k8s.aws/instance-network-bandwidth': '781',
        'karpenter.k8s.aws/instance-size': 'xlarge',
        'karpenter.sh/capacity-type': 'on-demand',
        'karpenter.sh/initialized': 'true',
        'karpenter.sh/nodepool': 'stable',
        'karpenter.sh/registered': 'true',
        'kubernetes.io/arch': 'amd64',
        'kubernetes.io/hostname': 'ip-10-0-27-85.eu-west-3.compute.internal',
        'kubernetes.io/os': 'linux',
        'node.kubernetes.io/instance-type': 'c7i-flex.xlarge',
        'topology.ebs.csi.aws.com/zone': 'eu-west-3a',
        'topology.k8s.aws/zone-id': 'euw3-az1',
        'topology.kubernetes.io/region': 'eu-west-3',
        'topology.kubernetes.io/zone': 'eu-west-3a',
      },
      annotations: {
        'alpha.kubernetes.io/provided-node-ip': '10.0.27.85',
        'compatibility.karpenter.k8s.aws/kubelet-drift-hash': '15379597991425564585',
        'csi.volume.kubernetes.io/nodeid': '{"ebs.csi.aws.com":"i-0e29559f842b2707d"}',
        'karpenter.k8s.aws/ec2nodeclass-hash': '12194261135232731854',
        'karpenter.k8s.aws/ec2nodeclass-hash-version': 'v3',
        'karpenter.sh/nodepool-hash': '13321557764212624671',
        'karpenter.sh/nodepool-hash-version': 'v3',
        'karpenter.sh/stored-version-migrated': 'true',
        'node.alpha.kubernetes.io/ttl': '0',
        'volumes.kubernetes.io/controller-managed-attach-detach': 'true',
      },
      addresses: [
        {
          type: 'InternalIP',
          address: '10.0.27.85',
        },
        {
          type: 'ExternalIP',
          address: '13.39.104.157',
        },
        {
          type: 'InternalDNS',
          address: 'ip-10-0-27-85.eu-west-3.compute.internal',
        },
        {
          type: 'Hostname',
          address: 'ip-10-0-27-85.eu-west-3.compute.internal',
        },
        {
          type: 'ExternalDNS',
          address: 'ec2-13-39-104-157.eu-west-3.compute.amazonaws.com',
        },
      ],
      pods: [
        {
          created_at: 1747200861000,
          name: 'aws-node-wvgdc',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 50,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 4,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 80,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 108,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'aws-eks-nodeagent':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon/aws-network-policy-agent:v1.2.0-eksbuild.1',
            'aws-node': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon-k8s-cni:v1.19.3-eksbuild.1',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200861000,
          name: 'ebs-csi-node-hvknd',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 30,
          cpu_milli_limit: null,
          memory_mib_request: 120,
          memory_mib_limit: 768,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 18,
            memory_percent_rss_usage: 2,
            memory_mib_working_set_usage: 21,
            memory_percent_working_set_usage: 2,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'ebs-plugin': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/aws-ebs-csi-driver:v1.40.0',
            'liveness-probe': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/livenessprobe:v2.14.0-eks-1-32-6',
            'node-driver-registrar':
              '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/csi-node-driver-registrar:v2.13.0-eks-1-32-6',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200861000,
          name: 'kube-proxy-m5vkq',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: null,
          memory_mib_request: 0,
          memory_mib_limit: null,
          metrics_usage: {
            cpu_milli_usage: 2,
            cpu_percent_usage: null,
            memory_mib_rss_usage: 14,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: 15,
            memory_percent_working_set_usage: null,
            disk_mib_usage: 1,
            disk_percent_usage: 0,
          },
          images_version: {
            'kube-proxy': '602401143452.dkr.ecr.eu-west-3.amazonaws.com/eks/kube-proxy:v1.31.3-minimal-eksbuild.2',
          },
          restart_count: 0,
        },
        {
          created_at: 1747200861000,
          name: 'promtail-ld42j',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 100,
          cpu_milli_limit: 100,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: 10,
            cpu_percent_usage: 10,
            memory_mib_rss_usage: 35,
            memory_percent_rss_usage: 27,
            memory_mib_working_set_usage: 38,
            memory_percent_working_set_usage: 29,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            promtail: 'public.ecr.aws/r3m4q3r9/pub-mirror-promtail:3.0.0',
          },
          restart_count: 0,
        },
        {
          created_at: 1747201199000,
          name: 'loki-0',
          namespace: 'logging',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 200,
          cpu_milli_limit: 666,
          memory_mib_request: 512,
          memory_mib_limit: 1024,
          metrics_usage: {
            cpu_milli_usage: 9,
            cpu_percent_usage: 1,
            memory_mib_rss_usage: 55,
            memory_percent_rss_usage: 5,
            memory_mib_working_set_usage: 57,
            memory_percent_working_set_usage: 5,
            disk_mib_usage: 3,
            disk_percent_usage: 0,
          },
          images_version: {
            loki: 'public.ecr.aws/r3m4q3r9/pub-mirror-loki:2.9.3',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159285000,
          name: 'nginx-ingress-ingress-nginx-controller-65c77984d-csckr',
          namespace: 'nginx-ingress',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 200,
          cpu_milli_limit: 700,
          memory_mib_request: 768,
          memory_mib_limit: 768,
          metrics_usage: {
            cpu_milli_usage: 1,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 39,
            memory_percent_rss_usage: 5,
            memory_mib_working_set_usage: 44,
            memory_percent_working_set_usage: 5,
            disk_mib_usage: 4,
            disk_percent_usage: 0,
          },
          images_version: {
            controller:
              'registry.k8s.io/ingress-nginx/controller:v1.11.5@sha256:a1cbad75b0a7098bf9325132794dddf9eef917e8a7fe246749a4cea7ff6f01eb',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159285000,
          name: 'app-zb6a2fda9-gitmzo-c486f69c5-r4hvm',
          namespace: 'z00665794-test',
          error_container_statuses: [
            {
              container_name: 'app-zb6a2fda9-gitmzo',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-mzottola-services-repository-git:13432785720330189640-879a6b3ea67a7b13ebd657cf97077a6a7d5ea180"',
            },
          ],
          qovery_service_info: {
            project_id: '018e3b90-744e-4174-adfb-3e1db59dce76',
            project_name: 'MelvinProject',
            environment_id: '00665794-e1f2-4a93-9a11-7c93674f1c9f',
            environment_name: 'test',
            service_id: 'b6a2fda9-46eb-4abb-943e-c8f21e38e57d',
            service_name: 'gitmzo',
          },
          cpu_milli_request: 100,
          cpu_milli_limit: 100,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-zb6a2fda9-gitmzo':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-mzottola-services-repository-git:13432785720330189640-879a6b3ea67a7b13ebd657cf97077a6a7d5ea180',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159285000,
          name: 'app-z5b00738b-http-test-clone-66dd675564-5ljlp',
          namespace: 'z15b3c8f9-production-demo',
          error_container_statuses: [
            {
              container_name: 'app-z5b00738b-http-test-clone',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-acarranoqovery-test-http-server-git:16596852535028700580-7b0395439bac416469322cffbb10760712226bda"',
            },
          ],
          qovery_service_info: {
            project_id: 'cf021d82-2c5e-41de-96eb-eb69c022eddc',
            project_name: '_Alessandro',
            environment_id: '15b3c8f9-443e-40ff-80e6-5bcc821d43b4',
            environment_name: 'production-demo',
            service_id: '5b00738b-dc67-4466-a9cb-83e3746ec85d',
            service_name: 'http-test-clone',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 52,
          memory_mib_limit: 52,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z5b00738b-http-test-clone':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-acarranoqovery-test-http-server-git:16596852535028700580-7b0395439bac416469322cffbb10760712226bda',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-z90505526-back-end-a-65b97bd6c4-tsvwh',
          namespace: 'z15b3c8f9-production-demo',
          error_container_statuses: [
            {
              container_name: 'app-z90505526-back-end-a',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-90505526-6c6e-4797-a381-b560b4d9ca99:stefanprodan.podinfo.6.5.2.90505526-6c6e-4797-a381-b560b4d9ca99"',
            },
          ],
          qovery_service_info: {
            project_id: 'cf021d82-2c5e-41de-96eb-eb69c022eddc',
            project_name: '_Alessandro',
            environment_id: '15b3c8f9-443e-40ff-80e6-5bcc821d43b4',
            environment_name: 'production-demo',
            service_id: '90505526-6c6e-4797-a381-b560b4d9ca99',
            service_name: 'back-end-A',
          },
          cpu_milli_request: 49,
          cpu_milli_limit: 49,
          memory_mib_request: 51,
          memory_mib_limit: 51,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z90505526-back-end-a':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-90505526-6c6e-4797-a381-b560b4d9ca99:stefanprodan.podinfo.6.5.2.90505526-6c6e-4797-a381-b560b4d9ca99',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159287000,
          name: 'postgres-z84c3bab1-postgresql-0',
          namespace: 'z15b3c8f9-production-demo',
          error_container_statuses: [],
          qovery_service_info: {
            project_id: 'cf021d82-2c5e-41de-96eb-eb69c022eddc',
            project_name: '_Alessandro',
            environment_id: '15b3c8f9-443e-40ff-80e6-5bcc821d43b4',
            environment_name: 'production-demo',
            service_id: '84c3bab1-0360-44b7-8dab-f6aa39c69439',
            service_name: 'postgresql',
          },
          cpu_milli_request: 500,
          cpu_milli_limit: 500,
          memory_mib_request: 512,
          memory_mib_limit: 512,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            postgresql: 'public.ecr.aws/r3m4q3r9/pub-mirror-postgresql:15',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-z04308de2-back-end-784747d9d6-9vzh9',
          namespace: 'z55867c71-production',
          error_container_statuses: [
            {
              container_name: 'app-z04308de2-back-end',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-04308de2-af27-405f-9e95-570fa94ed577:stefanprodan.podinfo.6.5.2.04308de2-af27-405f-9e95-570fa94ed577"',
            },
          ],
          qovery_service_info: {
            project_id: 'cf021d82-2c5e-41de-96eb-eb69c022eddc',
            project_name: '_Alessandro',
            environment_id: '55867c71-56f9-4b4f-ab22-5904c9dbafda',
            environment_name: 'production',
            service_id: '04308de2-af27-405f-9e95-570fa94ed577',
            service_name: 'back-end-A',
          },
          cpu_milli_request: 49,
          cpu_milli_limit: 49,
          memory_mib_request: 511,
          memory_mib_limit: 511,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z04308de2-back-end':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-04308de2-af27-405f-9e95-570fa94ed577:stefanprodan.podinfo.6.5.2.04308de2-af27-405f-9e95-570fa94ed577',
          },
          restart_count: 0,
        },
        {
          created_at: 1747216588000,
          name: 'app-z380a2d8f-console-5c67db958d-zwnn7',
          namespace: 'z579c273c-pr-staging-featservices-improve-toast-for-env-variabl',
          error_container_statuses: [],
          qovery_service_info: {
            project_id: 'a64f6cc1-4e34-433b-b8fd-5359716fb01b',
            project_name: 'R&D / Frontend',
            environment_id: '579c273c-a8aa-4dab-9824-6cfc3ec9d6ef',
            environment_name:
              '[PR] staging - feat(services): improve toast for env variable creation or update in case of conflict - 2025-05-14T09:31:05Z',
            service_id: '380a2d8f-6523-422b-95c2-e4084c9e9b37',
            service_name: 'console',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 50,
          memory_mib_limit: 50,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 3,
            memory_percent_rss_usage: 6,
            memory_mib_working_set_usage: 4,
            memory_percent_working_set_usage: 8,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'app-z380a2d8f-console':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-qovery-console-git:17403019626083079542-5cd293f26482bff76f7b136c24b5aefca6dc87ba',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159285000,
          name: 'app-z08e8fffb-app-6d6d67bb8c-h492d',
          namespace: 'z6006a85e-monorepo',
          error_container_statuses: [
            {
              container_name: 'app-z08e8fffb-app',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-acarranoqovery-monorepo-tetris-git:11545704217941601031-f994134a460864732eb6b5eb2c7c62c8315ab12c"',
            },
          ],
          qovery_service_info: {
            project_id: 'cf021d82-2c5e-41de-96eb-eb69c022eddc',
            project_name: '_Alessandro',
            environment_id: '6006a85e-20e1-4630-ba08-4428b477d008',
            environment_name: 'monorepo',
            service_id: '08e8fffb-b1ae-4863-9067-190f57c0ac3c',
            service_name: 'app1',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 51,
          memory_mib_limit: 51,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z08e8fffb-app':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-acarranoqovery-monorepo-tetris-git:11545704217941601031-f994134a460864732eb6b5eb2c7c62c8315ab12c',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-z14b1945f-app-8846f56cd-79cw7',
          namespace: 'z6006a85e-monorepo',
          error_container_statuses: [
            {
              container_name: 'app-z14b1945f-app',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-acarranoqovery-monorepo-tetris-git:18332440913750225835-f994134a460864732eb6b5eb2c7c62c8315ab12c"',
            },
          ],
          qovery_service_info: {
            project_id: 'cf021d82-2c5e-41de-96eb-eb69c022eddc',
            project_name: '_Alessandro',
            environment_id: '6006a85e-20e1-4630-ba08-4428b477d008',
            environment_name: 'monorepo',
            service_id: '14b1945f-0011-4153-8fe1-07de4eb104ec',
            service_name: 'app2',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 51,
          memory_mib_limit: 51,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z14b1945f-app':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-acarranoqovery-monorepo-tetris-git:18332440913750225835-f994134a460864732eb6b5eb2c7c62c8315ab12c',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-z05b8bc63-staging-first-app-c879b656-sq5nb',
          namespace: 'z8e0035d9-staging',
          error_container_statuses: [
            {
              container_name: 'app-z05b8bc63-staging-first-app',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-qovery-console-git:315955122544315374-f915333934819f041373b5cd8fff322e678ef347"',
            },
          ],
          qovery_service_info: {
            project_id: '566f48ec-bc41-4b5d-9209-2e6dbb381995',
            project_name: 'Romain Billard',
            environment_id: '8e0035d9-fffc-4829-9a0d-c13fdb637097',
            environment_name: 'Staging',
            service_id: '05b8bc63-4529-4f3f-aaac-90a58da1960e',
            service_name: 'Staging first app',
          },
          cpu_milli_request: 500,
          cpu_milli_limit: 500,
          memory_mib_request: 512,
          memory_mib_limit: 512,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z05b8bc63-staging-first-app':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-qovery-console-git:315955122544315374-f915333934819f041373b5cd8fff322e678ef347',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-z449efb6a-container-datadog-55c544bb6-tx7h2',
          namespace: 'z8e0035d9-staging',
          error_container_statuses: [
            {
              container_name: 'app-z449efb6a-container-datadog',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-449efb6a-3379-4a0f-b229-98ab34d9849f:datadog.agent.6.25.0-rc.11-jmx.449efb6a-3379-4a0f-b229-98ab34d9849f"',
            },
          ],
          qovery_service_info: {
            project_id: '566f48ec-bc41-4b5d-9209-2e6dbb381995',
            project_name: 'Romain Billard',
            environment_id: '8e0035d9-fffc-4829-9a0d-c13fdb637097',
            environment_name: 'Staging',
            service_id: '449efb6a-3379-4a0f-b229-98ab34d9849f',
            service_name: 'Container Datadog',
          },
          cpu_milli_request: 500,
          cpu_milli_limit: 500,
          memory_mib_request: 512,
          memory_mib_limit: 512,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z449efb6a-container-datadog':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-449efb6a-3379-4a0f-b229-98ab34d9849f:datadog.agent.6.25.0-rc.11-jmx.449efb6a-3379-4a0f-b229-98ab34d9849f',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-zebb84aa8-c8d6d977c-9g692',
          namespace: 'za64f6cc1-z28c47145',
          error_container_statuses: [],
          qovery_service_info: {
            project_id: 'a64f6cc1-4e34-433b-b8fd-5359716fb01b',
            project_name: 'R&D / Frontend',
            environment_id: '28c47145-c8e7-4b9d-8d9e-c65c95b48425',
            environment_name: 'staging',
            service_id: 'ebb84aa8-91c2-40fb-916d-3a158db354b7',
            service_name: 'console',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 50,
          memory_mib_limit: 50,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 3,
            memory_percent_rss_usage: 6,
            memory_mib_working_set_usage: 4,
            memory_percent_working_set_usage: 8,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'app-zebb84aa8':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-qovery-console-git:17403019626083079542-2a468376d5e3048895ec8eae49ae0761774b850a',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159285000,
          name: 'app-z758e4548-httpbin-55d85fb444-rgmb9',
          namespace: 'za95123ea-mlanie',
          error_container_statuses: [
            {
              container_name: 'app-z758e4548-httpbin',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-758e4548-0238-4717-8933-4e316ec5a947:kong.httpbin.0.2.3-rc.2.758e4548-0238-4717-8933-4e316ec5a947"',
            },
          ],
          qovery_service_info: {
            project_id: '7f96b59f-2821-433b-b41b-75304dbbca13',
            project_name: 'Mélanie',
            environment_id: 'a95123ea-a5f7-4730-95da-3557890df8d1',
            environment_name: 'Mélanie',
            service_id: '758e4548-0238-4717-8933-4e316ec5a947',
            service_name: 'HTTPBIN',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 51,
          memory_mib_limit: 51,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z758e4548-httpbin':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-758e4548-0238-4717-8933-4e316ec5a947:kong.httpbin.0.2.3-rc.2.758e4548-0238-4717-8933-4e316ec5a947',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-z7f3c1837-tetris-786fb56f9f-s89rr',
          namespace: 'za95123ea-mlanie',
          error_container_statuses: [
            {
              container_name: 'app-z7f3c1837-tetris',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-jul-dan-javascript-tetris-git:13432785720330189640-4df09ac467da7ae25b071d46cb11cf051659aadc"',
            },
          ],
          qovery_service_info: {
            project_id: '7f96b59f-2821-433b-b41b-75304dbbca13',
            project_name: 'Mélanie',
            environment_id: 'a95123ea-a5f7-4730-95da-3557890df8d1',
            environment_name: 'Mélanie',
            service_id: '7f3c1837-d7d5-40aa-b7c8-d644e4ff15a2',
            service_name: 'Tetris',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 51,
          memory_mib_limit: 51,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-z7f3c1837-tetris':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-jul-dan-javascript-tetris-git:13432785720330189640-4df09ac467da7ae25b071d46cb11cf051659aadc',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159285000,
          name: 'app-za9e492f5-console-75f6bc6c8f-qq55h',
          namespace: 'zb1cc6d03-dev',
          error_container_statuses: [],
          qovery_service_info: {
            project_id: 'a64f6cc1-4e34-433b-b8fd-5359716fb01b',
            project_name: 'R&D / Frontend',
            environment_id: 'b1cc6d03-1b9e-4536-b5ee-dc186c55218c',
            environment_name: 'dev',
            service_id: 'a9e492f5-a9f8-4f76-8f50-299221d58d9d',
            service_name: 'console',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 50,
          memory_mib_limit: 50,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 4,
            memory_percent_rss_usage: 8,
            memory_mib_working_set_usage: 6,
            memory_percent_working_set_usage: 12,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'app-za9e492f5-console':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-qovery-console-git:17276005374423926963-2a468376d5e3048895ec8eae49ae0761774b850a',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-zab1bf262-console-8696d5957b-5jkpb',
          namespace: 'ze12a2902-featcode-editor-variable-suggestion-frt-1268',
          error_container_statuses: [],
          qovery_service_info: {
            project_id: 'a64f6cc1-4e34-433b-b8fd-5359716fb01b',
            project_name: 'R&D / Frontend',
            environment_id: 'e12a2902-8071-4d9f-aa36-7cbfb6252d14',
            environment_name: 'feat/ai-copilot-QOV-640',
            service_id: 'ab1bf262-02ee-4794-b9f4-5e295613b663',
            service_name: 'console',
          },
          cpu_milli_request: 50,
          cpu_milli_limit: 50,
          memory_mib_request: 50,
          memory_mib_limit: 50,
          metrics_usage: {
            cpu_milli_usage: 0,
            cpu_percent_usage: 0,
            memory_mib_rss_usage: 3,
            memory_percent_rss_usage: 6,
            memory_mib_working_set_usage: 4,
            memory_percent_working_set_usage: 8,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            'app-zab1bf262-console':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/zc531a994-https-github-com-qovery-console-git:489653132693996735-5e9dc1329ff4897134e758f73d7e984bc65c0560',
          },
          restart_count: 0,
        },
        {
          created_at: 1747159286000,
          name: 'app-zccc48f6f-nginx-dcf8c8756-x2642',
          namespace: 'zee52471d-newkubeprometheusstack',
          error_container_statuses: [
            {
              container_name: 'app-zccc48f6f-nginx',
              reason: 'ImagePullBackOff',
              message:
                'Back-off pulling image "880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-ccc48f6f-ba76-4225-ab93-9a7cf5dd924f:nginx.1.25.2-alpine.ccc48f6f-ba76-4225-ab93-9a7cf5dd924f"',
            },
          ],
          qovery_service_info: {
            project_id: '018e3b90-744e-4174-adfb-3e1db59dce76',
            project_name: 'MelvinProject',
            environment_id: 'ee52471d-5054-41d7-aaab-a5c43b5ff34a',
            environment_name: 'newkubeprometheusstack',
            service_id: 'ccc48f6f-ba76-4225-ab93-9a7cf5dd924f',
            service_name: 'nginx',
          },
          cpu_milli_request: 100,
          cpu_milli_limit: 100,
          memory_mib_request: 128,
          memory_mib_limit: 128,
          metrics_usage: {
            cpu_milli_usage: null,
            cpu_percent_usage: null,
            memory_mib_rss_usage: null,
            memory_percent_rss_usage: null,
            memory_mib_working_set_usage: null,
            memory_percent_working_set_usage: null,
            disk_mib_usage: null,
            disk_percent_usage: null,
          },
          images_version: {
            'app-zccc48f6f-nginx':
              '880317640327.dkr.ecr.eu-west-3.amazonaws.com/qovery-mirror-ccc48f6f-ba76-4225-ab93-9a7cf5dd924f:nginx.1.25.2-alpine.ccc48f6f-ba76-4225-ab93-9a7cf5dd924f',
          },
          restart_count: 0,
        },
      ],
      metrics_usage: {
        cpu_milli_usage: 76,
        cpu_percent_usage: 1,
        memory_mib_rss_usage: 485,
        memory_percent_rss_usage: 7,
        memory_mib_working_set_usage: 921,
        memory_percent_working_set_usage: 13,
        disk_mib_usage: 386,
        disk_percent_usage: 2,
      },
    },
    {
      created_at: 1747200803000,
      name: 'fargate-ip-10-0-166-226.eu-west-3.compute.internal',
      architecture: 'amd64',
      instance_type: null,
      kernel_version: '5.10.235-227.919.amzn2.x86_64',
      kubelet_version: 'v1.31.4-eks-2d5f260',
      operating_system: 'linux',
      os_image: 'Amazon Linux 2',
      unschedulable: false,
      resources_allocatable: {
        cpu_milli: 2000,
        memory_mib: 3750,
        ephemeral_storage_mib: 16384,
        pods: 1,
      },
      resources_allocated: {
        memory_mib: 1024,
        cpu_milli: 1000,
      },
      taints: [
        {
          key: 'eks.amazonaws.com/compute-type',
          value: 'fargate',
          effect: 'NoSchedule',
        },
      ],
      conditions: [
        {
          type: 'MemoryPressure',
          status: 'False',
          last_heartbeat_time: 1747216446000,
          last_transition_time: 1747200803000,
          reason: 'KubeletHasSufficientMemory',
          message: 'kubelet has sufficient memory available',
        },
        {
          type: 'DiskPressure',
          status: 'False',
          last_heartbeat_time: 1747216446000,
          last_transition_time: 1747200803000,
          reason: 'KubeletHasNoDiskPressure',
          message: 'kubelet has no disk pressure',
        },
        {
          type: 'PIDPressure',
          status: 'False',
          last_heartbeat_time: 1747216446000,
          last_transition_time: 1747200803000,
          reason: 'KubeletHasSufficientPID',
          message: 'kubelet has sufficient PID available',
        },
        {
          type: 'Ready',
          status: 'True',
          last_heartbeat_time: 1747216446000,
          last_transition_time: 1747200804000,
          reason: 'KubeletReady',
          message: 'kubelet is posting ready status',
        },
      ],
      labels: {
        'beta.kubernetes.io/arch': 'amd64',
        'beta.kubernetes.io/os': 'linux',
        'eks.amazonaws.com/compute-type': 'fargate',
        'failure-domain.beta.kubernetes.io/region': 'eu-west-3',
        'failure-domain.beta.kubernetes.io/zone': 'eu-west-3a',
        'kubernetes.io/arch': 'amd64',
        'kubernetes.io/hostname': 'fargate-ip-10-0-166-226.eu-west-3.compute.internal',
        'kubernetes.io/os': 'linux',
        'topology.k8s.aws/zone-id': 'euw3-az1',
        'topology.kubernetes.io/region': 'eu-west-3',
        'topology.kubernetes.io/zone': 'eu-west-3a',
      },
      annotations: {
        'node.alpha.kubernetes.io/ttl': '0',
        'volumes.kubernetes.io/controller-managed-attach-detach': 'true',
      },
      addresses: [
        {
          type: 'InternalIP',
          address: '10.0.166.226',
        },
        {
          type: 'InternalDNS',
          address: 'ip-10-0-166-226.eu-west-3.compute.internal',
        },
        {
          type: 'Hostname',
          address: 'fargate-ip-10-0-166-226.eu-west-3.compute.internal',
        },
      ],
      pods: [
        {
          created_at: 1747200765000,
          name: 'karpenter-6c865f5875-5chbr',
          namespace: 'kube-system',
          error_container_statuses: [],
          qovery_service_info: null,
          cpu_milli_request: 1000,
          cpu_milli_limit: 1000,
          memory_mib_request: 1024,
          memory_mib_limit: 1024,
          metrics_usage: {
            cpu_milli_usage: 14,
            cpu_percent_usage: 1,
            memory_mib_rss_usage: 239,
            memory_percent_rss_usage: 23,
            memory_mib_working_set_usage: 241,
            memory_percent_working_set_usage: 23,
            disk_mib_usage: 0,
            disk_percent_usage: 0,
          },
          images_version: {
            controller:
              'public.ecr.aws/karpenter/controller:1.0.9@sha256:80b2d0bf045ea5c02cc4abfc5f73cfea41dea772aa2e52c77bcadbaa27ed1ea0',
          },
          restart_count: 0,
        },
      ],
      metrics_usage: {
        cpu_milli_usage: 97,
        cpu_percent_usage: 4,
        memory_mib_rss_usage: 332,
        memory_percent_rss_usage: 8,
        memory_mib_working_set_usage: 358,
        memory_percent_working_set_usage: 9,
        disk_mib_usage: 3636,
        disk_percent_usage: 22,
      },
    },
  ],
  pvcs: [],
  node_pools: [
    {
      name: 'default',
      nodes_count: 1,
      cpu_milli: 4000,
      memory_mib: 15614,
      cpu_milli_limit: null,
      memory_mib_limit: null,
    },
    {
      name: 'stable',
      nodes_count: 2,
      cpu_milli: 6000,
      memory_mib: 9702,
      cpu_milli_limit: null,
      memory_mib_limit: null,
    },
  ],
  tls_certificate: {
    dns_names: ['*.zc531a994.rustrocks.cloud'],
    not_before: 1745901462000,
    not_after: 1753677461000,
    renewal_time: 1751085461000,
    state: 'RUNNING',
    state_message: 'Certificate is up to date and has not expired',
    failed_issuance_attempt_count: 0,
    last_failure_issuance_time: null,
  },
}
