import { type TerraformBackend } from 'qovery-typescript-axios'

// No backend means the default one: the Kubernetes backend generated by Qovery
export function isKubernetesBackend(backend?: TerraformBackend): boolean {
  return !backend || 'kubernetes' in backend
}
