export enum IconEnum {
  GITHUB = 'GITHUB',
  GITLAB = 'GITLAB',
  BITBUCKET = 'BITBUCKET',
  ENVIRONMENT = 'ENVIRONMENT',
  APPLICATIONS = 'APPLICATIONS',
  APPLICATION = 'APPLICATION',
  AWS = 'AWS',
}
