export enum RunningStatus {
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  TERMINATED = 'TERMINATED',
  UNKNOWN = 'UNKNOWN',
  COMPLETED = 'COMPLETED',
}
