export enum RunningState {
  STARTING = 'STARTING',
  DEPLOYED = 'DEPLOYED',
  RUNNING = 'RUNNING',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  UNKNOWN = 'UNKNOWN',
  COMPLETED = 'COMPLETED',
}
