export enum ServiceTypeEnum {
  DATABASE = 'DATABASE',
  APPLICATION = 'APPLICATION',
  CONTAINER = 'CONTAINER',
  JOB = 'JOB',
  CRON_JOB = 'CRON_JOB',
  LIFECYCLE_JOB = 'LIFECYCLE_JOB',
  HELM = 'HELM',
}
