/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedOrganizationOrganizationIdClusterIdIndexRouteImport } from './routes/_authenticated/organization/$organizationId/$clusterId/index'
import { Route as AuthenticatedOrganizationOrganizationIdAlertsRouteImport } from './routes/_authenticated/organization/$organizationId/alerts'
import { Route as AuthenticatedOrganizationOrganizationIdAuditLogsRouteImport } from './routes/_authenticated/organization/$organizationId/audit-logs'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/cluster-logs'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/index'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/overview'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/advanced-settings'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/credentials'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/danger-zone'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/general'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/image-registry'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/index'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/resources'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/settings/route'
import { Route as AuthenticatedOrganizationOrganizationIdClustersRouteImport } from './routes/_authenticated/organization/$organizationId/clusters'
import { Route as AuthenticatedOrganizationOrganizationIdIndexRouteImport } from './routes/_authenticated/organization/$organizationId/index'
import { Route as AuthenticatedOrganizationOrganizationIdOverviewRouteImport } from './routes/_authenticated/organization/$organizationId/overview'
import { Route as AuthenticatedOrganizationOrganizationIdSettingsRouteImport } from './routes/_authenticated/organization/$organizationId/settings'
import { Route as AuthenticatedOrganizationIndexRouteImport } from './routes/_authenticated/organization/index'
import { Route as AuthenticatedOrganizationRouteRouteImport } from './routes/_authenticated/organization/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginAuth0CallbackRouteImport } from './routes/login/auth0-callback'
import { Route as LoginIndexRouteImport } from './routes/login/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAuth0CallbackRoute = LoginAuth0CallbackRouteImport.update({
  id: '/login/auth0-callback',
  path: '/login/auth0-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationRouteRoute = AuthenticatedOrganizationRouteRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationIndexRoute = AuthenticatedOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOrganizationRouteRoute,
} as any)
const AuthenticatedOrganizationOrganizationIdIndexRoute =
  AuthenticatedOrganizationOrganizationIdIndexRouteImport.update({
    id: '/$organizationId/',
    path: '/$organizationId/',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdSettingsRoute =
  AuthenticatedOrganizationOrganizationIdSettingsRouteImport.update({
    id: '/$organizationId/settings',
    path: '/$organizationId/settings',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdOverviewRoute =
  AuthenticatedOrganizationOrganizationIdOverviewRouteImport.update({
    id: '/$organizationId/overview',
    path: '/$organizationId/overview',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClustersRoute =
  AuthenticatedOrganizationOrganizationIdClustersRouteImport.update({
    id: '/$organizationId/clusters',
    path: '/$organizationId/clusters',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdAuditLogsRoute =
  AuthenticatedOrganizationOrganizationIdAuditLogsRouteImport.update({
    id: '/$organizationId/audit-logs',
    path: '/$organizationId/audit-logs',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdAlertsRoute =
  AuthenticatedOrganizationOrganizationIdAlertsRouteImport.update({
    id: '/$organizationId/alerts',
    path: '/$organizationId/alerts',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute =
  AuthenticatedOrganizationOrganizationIdClusterIdIndexRouteImport.update({
    id: '/$organizationId/$clusterId/',
    path: '/$organizationId/$clusterId/',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRouteImport.update({
    id: '/$organizationId/cluster/$clusterId/',
    path: '/$organizationId/cluster/$clusterId/',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRouteImport.update({
    id: '/$organizationId/cluster/$clusterId/overview',
    path: '/$organizationId/cluster/$clusterId/overview',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRouteImport.update({
    id: '/$organizationId/cluster/$clusterId/cluster-logs',
    path: '/$organizationId/cluster/$clusterId/cluster-logs',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteImport.update({
    id: '/$organizationId/cluster/$clusterId/settings',
    path: '/$organizationId/cluster/$clusterId/settings',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRouteImport.update({
    id: '/image-registry',
    path: '/image-registry',
    getParentRoute: () => AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRouteImport.update({
    id: '/danger-zone',
    path: '/danger-zone',
    getParentRoute: () => AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRouteImport.update({
    id: '/advanced-settings',
    path: '/advanced-settings',
    getParentRoute: () => AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organization': typeof AuthenticatedOrganizationRouteRouteWithChildren
  '/login/auth0-callback': typeof LoginAuth0CallbackRoute
  '/login': typeof LoginIndexRoute
  '/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/organization/$organizationId/alerts': typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  '/organization/$organizationId/audit-logs': typeof AuthenticatedOrganizationOrganizationIdAuditLogsRoute
  '/organization/$organizationId/clusters': typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  '/organization/$organizationId/overview': typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  '/organization/$organizationId/settings': typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  '/organization/$organizationId': typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  '/organization/$organizationId/$clusterId': typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  '/organization/$organizationId/cluster/$clusterId/settings': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteWithChildren
  '/organization/$organizationId/cluster/$clusterId/cluster-logs': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute
  '/organization/$organizationId/cluster/$clusterId/overview': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
  '/organization/$organizationId/cluster/$clusterId': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute
  '/organization/$organizationId/cluster/$clusterId/settings/advanced-settings': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute
  '/organization/$organizationId/cluster/$clusterId/settings/credentials': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute
  '/organization/$organizationId/cluster/$clusterId/settings/danger-zone': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute
  '/organization/$organizationId/cluster/$clusterId/settings/general': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute
  '/organization/$organizationId/cluster/$clusterId/settings/image-registry': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute
  '/organization/$organizationId/cluster/$clusterId/settings/resources': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute
  '/organization/$organizationId/cluster/$clusterId/settings/': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/auth0-callback': typeof LoginAuth0CallbackRoute
  '/login': typeof LoginIndexRoute
  '/organization': typeof AuthenticatedOrganizationIndexRoute
  '/organization/$organizationId/alerts': typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  '/organization/$organizationId/audit-logs': typeof AuthenticatedOrganizationOrganizationIdAuditLogsRoute
  '/organization/$organizationId/clusters': typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  '/organization/$organizationId/overview': typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  '/organization/$organizationId/settings': typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  '/organization/$organizationId': typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  '/organization/$organizationId/$clusterId': typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  '/organization/$organizationId/cluster/$clusterId/cluster-logs': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute
  '/organization/$organizationId/cluster/$clusterId/overview': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
  '/organization/$organizationId/cluster/$clusterId': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute
  '/organization/$organizationId/cluster/$clusterId/settings/advanced-settings': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute
  '/organization/$organizationId/cluster/$clusterId/settings/credentials': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute
  '/organization/$organizationId/cluster/$clusterId/settings/danger-zone': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute
  '/organization/$organizationId/cluster/$clusterId/settings/general': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute
  '/organization/$organizationId/cluster/$clusterId/settings/image-registry': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute
  '/organization/$organizationId/cluster/$clusterId/settings/resources': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute
  '/organization/$organizationId/cluster/$clusterId/settings': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/organization': typeof AuthenticatedOrganizationRouteRouteWithChildren
  '/login/auth0-callback': typeof LoginAuth0CallbackRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/_authenticated/organization/$organizationId/alerts': typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  '/_authenticated/organization/$organizationId/audit-logs': typeof AuthenticatedOrganizationOrganizationIdAuditLogsRoute
  '/_authenticated/organization/$organizationId/clusters': typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  '/_authenticated/organization/$organizationId/overview': typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  '/_authenticated/organization/$organizationId/settings': typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  '/_authenticated/organization/$organizationId/': typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  '/_authenticated/organization/$organizationId/$clusterId/': typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteWithChildren
  '/_authenticated/organization/$organizationId/cluster/$clusterId/cluster-logs': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/overview': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/advanced-settings': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/credentials': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/danger-zone': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/general': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/image-registry': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/resources': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organization'
    | '/login/auth0-callback'
    | '/login'
    | '/organization/'
    | '/organization/$organizationId/alerts'
    | '/organization/$organizationId/audit-logs'
    | '/organization/$organizationId/clusters'
    | '/organization/$organizationId/overview'
    | '/organization/$organizationId/settings'
    | '/organization/$organizationId'
    | '/organization/$organizationId/$clusterId'
    | '/organization/$organizationId/cluster/$clusterId/settings'
    | '/organization/$organizationId/cluster/$clusterId/cluster-logs'
    | '/organization/$organizationId/cluster/$clusterId/overview'
    | '/organization/$organizationId/cluster/$clusterId'
    | '/organization/$organizationId/cluster/$clusterId/settings/advanced-settings'
    | '/organization/$organizationId/cluster/$clusterId/settings/credentials'
    | '/organization/$organizationId/cluster/$clusterId/settings/danger-zone'
    | '/organization/$organizationId/cluster/$clusterId/settings/general'
    | '/organization/$organizationId/cluster/$clusterId/settings/image-registry'
    | '/organization/$organizationId/cluster/$clusterId/settings/resources'
    | '/organization/$organizationId/cluster/$clusterId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/auth0-callback'
    | '/login'
    | '/organization'
    | '/organization/$organizationId/alerts'
    | '/organization/$organizationId/audit-logs'
    | '/organization/$organizationId/clusters'
    | '/organization/$organizationId/overview'
    | '/organization/$organizationId/settings'
    | '/organization/$organizationId'
    | '/organization/$organizationId/$clusterId'
    | '/organization/$organizationId/cluster/$clusterId/cluster-logs'
    | '/organization/$organizationId/cluster/$clusterId/overview'
    | '/organization/$organizationId/cluster/$clusterId'
    | '/organization/$organizationId/cluster/$clusterId/settings/advanced-settings'
    | '/organization/$organizationId/cluster/$clusterId/settings/credentials'
    | '/organization/$organizationId/cluster/$clusterId/settings/danger-zone'
    | '/organization/$organizationId/cluster/$clusterId/settings/general'
    | '/organization/$organizationId/cluster/$clusterId/settings/image-registry'
    | '/organization/$organizationId/cluster/$clusterId/settings/resources'
    | '/organization/$organizationId/cluster/$clusterId/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/organization'
    | '/login/auth0-callback'
    | '/login/'
    | '/_authenticated/organization/'
    | '/_authenticated/organization/$organizationId/alerts'
    | '/_authenticated/organization/$organizationId/audit-logs'
    | '/_authenticated/organization/$organizationId/clusters'
    | '/_authenticated/organization/$organizationId/overview'
    | '/_authenticated/organization/$organizationId/settings'
    | '/_authenticated/organization/$organizationId/'
    | '/_authenticated/organization/$organizationId/$clusterId/'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/cluster-logs'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/overview'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/advanced-settings'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/credentials'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/danger-zone'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/general'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/image-registry'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/resources'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginAuth0CallbackRoute: typeof LoginAuth0CallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/auth0-callback': {
      id: '/login/auth0-callback'
      path: '/login/auth0-callback'
      fullPath: '/login/auth0-callback'
      preLoaderRoute: typeof LoginAuth0CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organization/': {
      id: '/_authenticated/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AuthenticatedOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/': {
      id: '/_authenticated/organization/$organizationId/'
      path: '/$organizationId'
      fullPath: '/organization/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/settings': {
      id: '/_authenticated/organization/$organizationId/settings'
      path: '/$organizationId/settings'
      fullPath: '/organization/$organizationId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/overview': {
      id: '/_authenticated/organization/$organizationId/overview'
      path: '/$organizationId/overview'
      fullPath: '/organization/$organizationId/overview'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdOverviewRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/clusters': {
      id: '/_authenticated/organization/$organizationId/clusters'
      path: '/$organizationId/clusters'
      fullPath: '/organization/$organizationId/clusters'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClustersRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/audit-logs': {
      id: '/_authenticated/organization/$organizationId/audit-logs'
      path: '/$organizationId/audit-logs'
      fullPath: '/organization/$organizationId/audit-logs'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdAuditLogsRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/alerts': {
      id: '/_authenticated/organization/$organizationId/alerts'
      path: '/$organizationId/alerts'
      fullPath: '/organization/$organizationId/alerts'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdAlertsRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/$clusterId/': {
      id: '/_authenticated/organization/$organizationId/$clusterId/'
      path: '/$organizationId/$clusterId'
      fullPath: '/organization/$organizationId/$clusterId'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/'
      path: '/$organizationId/cluster/$clusterId'
      fullPath: '/organization/$organizationId/cluster/$clusterId'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/overview': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/overview'
      path: '/$organizationId/cluster/$clusterId/overview'
      fullPath: '/organization/$organizationId/cluster/$clusterId/overview'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/cluster-logs': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/cluster-logs'
      path: '/$organizationId/cluster/$clusterId/cluster-logs'
      fullPath: '/organization/$organizationId/cluster/$clusterId/cluster-logs'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings'
      path: '/$organizationId/cluster/$clusterId/settings'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/'
      path: '/'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings/'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/resources': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/resources'
      path: '/resources'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings/resources'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRouteImport
      parentRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/image-registry': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/image-registry'
      path: '/image-registry'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings/image-registry'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRouteImport
      parentRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/general': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/general'
      path: '/general'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings/general'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/danger-zone': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/danger-zone'
      path: '/danger-zone'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings/danger-zone'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRouteImport
      parentRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/credentials': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/credentials'
      path: '/credentials'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings/credentials'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRouteImport
      parentRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/advanced-settings': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/settings/advanced-settings'
      path: '/advanced-settings'
      fullPath: '/organization/$organizationId/cluster/$clusterId/settings/advanced-settings'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute
    }
  }
}

interface AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteChildren {
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute
}

const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteChildren: AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteChildren =
  {
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute:
      AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsAdvancedSettingsRoute,
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute:
      AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsCredentialsRoute,
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute:
      AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsDangerZoneRoute,
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute:
      AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsGeneralRoute,
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute:
      AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsImageRegistryRoute,
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute:
      AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsResourcesRoute,
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute:
      AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsIndexRoute,
  }

const AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteWithChildren =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute._addFileChildren(
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteChildren
  )

interface AuthenticatedOrganizationRouteRouteChildren {
  AuthenticatedOrganizationIndexRoute: typeof AuthenticatedOrganizationIndexRoute
  AuthenticatedOrganizationOrganizationIdAlertsRoute: typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  AuthenticatedOrganizationOrganizationIdAuditLogsRoute: typeof AuthenticatedOrganizationOrganizationIdAuditLogsRoute
  AuthenticatedOrganizationOrganizationIdClustersRoute: typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  AuthenticatedOrganizationOrganizationIdOverviewRoute: typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  AuthenticatedOrganizationOrganizationIdSettingsRoute: typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  AuthenticatedOrganizationOrganizationIdIndexRoute: typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute: typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteWithChildren
  AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute
}

const AuthenticatedOrganizationRouteRouteChildren: AuthenticatedOrganizationRouteRouteChildren = {
  AuthenticatedOrganizationIndexRoute: AuthenticatedOrganizationIndexRoute,
  AuthenticatedOrganizationOrganizationIdAlertsRoute: AuthenticatedOrganizationOrganizationIdAlertsRoute,
  AuthenticatedOrganizationOrganizationIdAuditLogsRoute: AuthenticatedOrganizationOrganizationIdAuditLogsRoute,
  AuthenticatedOrganizationOrganizationIdClustersRoute: AuthenticatedOrganizationOrganizationIdClustersRoute,
  AuthenticatedOrganizationOrganizationIdOverviewRoute: AuthenticatedOrganizationOrganizationIdOverviewRoute,
  AuthenticatedOrganizationOrganizationIdSettingsRoute: AuthenticatedOrganizationOrganizationIdSettingsRoute,
  AuthenticatedOrganizationOrganizationIdIndexRoute: AuthenticatedOrganizationOrganizationIdIndexRoute,
  AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute:
    AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute,
  AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRoute:
    AuthenticatedOrganizationOrganizationIdClusterClusterIdSettingsRouteRouteWithChildren,
  AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute:
    AuthenticatedOrganizationOrganizationIdClusterClusterIdClusterLogsRoute,
  AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute:
    AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute,
  AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute:
    AuthenticatedOrganizationOrganizationIdClusterClusterIdIndexRoute,
}

const AuthenticatedOrganizationRouteRouteWithChildren = AuthenticatedOrganizationRouteRoute._addFileChildren(
  AuthenticatedOrganizationRouteRouteChildren
)

interface AuthenticatedRouteChildren {
  AuthenticatedOrganizationRouteRoute: typeof AuthenticatedOrganizationRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrganizationRouteRoute: AuthenticatedOrganizationRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginAuth0CallbackRoute: LoginAuth0CallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
