/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedOrganizationOrganizationIdClusterIdIndexRouteImport } from './routes/_authenticated/organization/$organizationId/$clusterId/index'
import { Route as AuthenticatedOrganizationOrganizationIdAlertsRouteImport } from './routes/_authenticated/organization/$organizationId/alerts'
import { Route as AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRouteImport } from './routes/_authenticated/organization/$organizationId/cluster/$clusterId/overview'
import { Route as AuthenticatedOrganizationOrganizationIdClustersRouteImport } from './routes/_authenticated/organization/$organizationId/clusters'
import { Route as AuthenticatedOrganizationOrganizationIdIndexRouteImport } from './routes/_authenticated/organization/$organizationId/index'
import { Route as AuthenticatedOrganizationOrganizationIdOverviewRouteImport } from './routes/_authenticated/organization/$organizationId/overview'
import { Route as AuthenticatedOrganizationOrganizationIdSecurityRouteImport } from './routes/_authenticated/organization/$organizationId/security'
import { Route as AuthenticatedOrganizationOrganizationIdSettingsRouteImport } from './routes/_authenticated/organization/$organizationId/settings'
import { Route as AuthenticatedOrganizationIndexRouteImport } from './routes/_authenticated/organization/index'
import { Route as AuthenticatedOrganizationRouteRouteImport } from './routes/_authenticated/organization/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginAuth0CallbackRouteImport } from './routes/login/auth0-callback'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OrganizationOrgIdAlertsRouteImport } from './routes/organization/$orgId/alerts'
import { Route as OrganizationOrgIdClustersRouteImport } from './routes/organization/$orgId/clusters'
import { Route as OrganizationOrgIdIndexRouteImport } from './routes/organization/$orgId/index'
import { Route as OrganizationOrgIdOverviewRouteImport } from './routes/organization/$orgId/overview'
import { Route as OrganizationOrgIdSecurityRouteImport } from './routes/organization/$orgId/security'
import { Route as OrganizationOrgIdSettingsRouteImport } from './routes/organization/$orgId/settings'
import { Route as OrganizationIndexRouteImport } from './routes/organization/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAuth0CallbackRoute = LoginAuth0CallbackRouteImport.update({
  id: '/login/auth0-callback',
  path: '/login/auth0-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationRouteRoute = AuthenticatedOrganizationRouteRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OrganizationOrgIdIndexRoute = OrganizationOrgIdIndexRouteImport.update({
  id: '/organization/$orgId/',
  path: '/organization/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationIndexRoute = AuthenticatedOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOrganizationRouteRoute,
} as any)
const OrganizationOrgIdSettingsRoute = OrganizationOrgIdSettingsRouteImport.update({
  id: '/organization/$orgId/settings',
  path: '/organization/$orgId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrgIdSecurityRoute = OrganizationOrgIdSecurityRouteImport.update({
  id: '/organization/$orgId/security',
  path: '/organization/$orgId/security',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrgIdOverviewRoute = OrganizationOrgIdOverviewRouteImport.update({
  id: '/organization/$orgId/overview',
  path: '/organization/$orgId/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrgIdClustersRoute = OrganizationOrgIdClustersRouteImport.update({
  id: '/organization/$orgId/clusters',
  path: '/organization/$orgId/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrgIdAlertsRoute = OrganizationOrgIdAlertsRouteImport.update({
  id: '/organization/$orgId/alerts',
  path: '/organization/$orgId/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationOrganizationIdIndexRoute =
  AuthenticatedOrganizationOrganizationIdIndexRouteImport.update({
    id: '/$organizationId/',
    path: '/$organizationId/',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdSettingsRoute =
  AuthenticatedOrganizationOrganizationIdSettingsRouteImport.update({
    id: '/$organizationId/settings',
    path: '/$organizationId/settings',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdSecurityRoute =
  AuthenticatedOrganizationOrganizationIdSecurityRouteImport.update({
    id: '/$organizationId/security',
    path: '/$organizationId/security',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdOverviewRoute =
  AuthenticatedOrganizationOrganizationIdOverviewRouteImport.update({
    id: '/$organizationId/overview',
    path: '/$organizationId/overview',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClustersRoute =
  AuthenticatedOrganizationOrganizationIdClustersRouteImport.update({
    id: '/$organizationId/clusters',
    path: '/$organizationId/clusters',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdAlertsRoute =
  AuthenticatedOrganizationOrganizationIdAlertsRouteImport.update({
    id: '/$organizationId/alerts',
    path: '/$organizationId/alerts',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute =
  AuthenticatedOrganizationOrganizationIdClusterIdIndexRouteImport.update({
    id: '/$organizationId/$clusterId/',
    path: '/$organizationId/$clusterId/',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)
const AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute =
  AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRouteImport.update({
    id: '/$organizationId/cluster/$clusterId/overview',
    path: '/$organizationId/cluster/$clusterId/overview',
    getParentRoute: () => AuthenticatedOrganizationRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/login/auth0-callback': typeof LoginAuth0CallbackRoute
  '/login': typeof LoginIndexRoute
  '/organization/$orgId/alerts': typeof OrganizationOrgIdAlertsRoute
  '/organization/$orgId/clusters': typeof OrganizationOrgIdClustersRoute
  '/organization/$orgId/overview': typeof OrganizationOrgIdOverviewRoute
  '/organization/$orgId/security': typeof OrganizationOrgIdSecurityRoute
  '/organization/$orgId/settings': typeof OrganizationOrgIdSettingsRoute
  '/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/organization/$orgId': typeof OrganizationOrgIdIndexRoute
  '/organization/$organizationId/alerts': typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  '/organization/$organizationId/clusters': typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  '/organization/$organizationId/overview': typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  '/organization/$organizationId/security': typeof AuthenticatedOrganizationOrganizationIdSecurityRoute
  '/organization/$organizationId/settings': typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  '/organization/$organizationId': typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  '/organization/$organizationId/$clusterId': typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  '/organization/$organizationId/cluster/$clusterId/overview': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/auth0-callback': typeof LoginAuth0CallbackRoute
  '/login': typeof LoginIndexRoute
  '/organization': typeof AuthenticatedOrganizationIndexRoute
  '/organization/$orgId/alerts': typeof OrganizationOrgIdAlertsRoute
  '/organization/$orgId/clusters': typeof OrganizationOrgIdClustersRoute
  '/organization/$orgId/overview': typeof OrganizationOrgIdOverviewRoute
  '/organization/$orgId/security': typeof OrganizationOrgIdSecurityRoute
  '/organization/$orgId/settings': typeof OrganizationOrgIdSettingsRoute
  '/organization/$orgId': typeof OrganizationOrgIdIndexRoute
  '/organization/$organizationId/alerts': typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  '/organization/$organizationId/clusters': typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  '/organization/$organizationId/overview': typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  '/organization/$organizationId/security': typeof AuthenticatedOrganizationOrganizationIdSecurityRoute
  '/organization/$organizationId/settings': typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  '/organization/$organizationId': typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  '/organization/$organizationId/$clusterId': typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  '/organization/$organizationId/cluster/$clusterId/overview': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/organization': typeof AuthenticatedOrganizationRouteRouteWithChildren
  '/login/auth0-callback': typeof LoginAuth0CallbackRoute
  '/login/': typeof LoginIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/organization/$orgId/alerts': typeof OrganizationOrgIdAlertsRoute
  '/organization/$orgId/clusters': typeof OrganizationOrgIdClustersRoute
  '/organization/$orgId/overview': typeof OrganizationOrgIdOverviewRoute
  '/organization/$orgId/security': typeof OrganizationOrgIdSecurityRoute
  '/organization/$orgId/settings': typeof OrganizationOrgIdSettingsRoute
  '/_authenticated/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/organization/$orgId/': typeof OrganizationOrgIdIndexRoute
  '/_authenticated/organization/$organizationId/alerts': typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  '/_authenticated/organization/$organizationId/clusters': typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  '/_authenticated/organization/$organizationId/overview': typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  '/_authenticated/organization/$organizationId/security': typeof AuthenticatedOrganizationOrganizationIdSecurityRoute
  '/_authenticated/organization/$organizationId/settings': typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  '/_authenticated/organization/$organizationId/': typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  '/_authenticated/organization/$organizationId/$clusterId/': typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  '/_authenticated/organization/$organizationId/cluster/$clusterId/overview': typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organization'
    | '/login/auth0-callback'
    | '/login'
    | '/organization/$orgId/alerts'
    | '/organization/$orgId/clusters'
    | '/organization/$orgId/overview'
    | '/organization/$orgId/security'
    | '/organization/$orgId/settings'
    | '/organization/'
    | '/organization/$orgId'
    | '/organization/$organizationId/alerts'
    | '/organization/$organizationId/clusters'
    | '/organization/$organizationId/overview'
    | '/organization/$organizationId/security'
    | '/organization/$organizationId/settings'
    | '/organization/$organizationId'
    | '/organization/$organizationId/$clusterId'
    | '/organization/$organizationId/cluster/$clusterId/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/auth0-callback'
    | '/login'
    | '/organization'
    | '/organization/$orgId/alerts'
    | '/organization/$orgId/clusters'
    | '/organization/$orgId/overview'
    | '/organization/$orgId/security'
    | '/organization/$orgId/settings'
    | '/organization/$orgId'
    | '/organization/$organizationId/alerts'
    | '/organization/$organizationId/clusters'
    | '/organization/$organizationId/overview'
    | '/organization/$organizationId/security'
    | '/organization/$organizationId/settings'
    | '/organization/$organizationId'
    | '/organization/$organizationId/$clusterId'
    | '/organization/$organizationId/cluster/$clusterId/overview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/organization'
    | '/login/auth0-callback'
    | '/login/'
    | '/organization/'
    | '/organization/$orgId/alerts'
    | '/organization/$orgId/clusters'
    | '/organization/$orgId/overview'
    | '/organization/$orgId/security'
    | '/organization/$orgId/settings'
    | '/_authenticated/organization/'
    | '/organization/$orgId/'
    | '/_authenticated/organization/$organizationId/alerts'
    | '/_authenticated/organization/$organizationId/clusters'
    | '/_authenticated/organization/$organizationId/overview'
    | '/_authenticated/organization/$organizationId/security'
    | '/_authenticated/organization/$organizationId/settings'
    | '/_authenticated/organization/$organizationId/'
    | '/_authenticated/organization/$organizationId/$clusterId/'
    | '/_authenticated/organization/$organizationId/cluster/$clusterId/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginAuth0CallbackRoute: typeof LoginAuth0CallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  OrganizationOrgIdAlertsRoute: typeof OrganizationOrgIdAlertsRoute
  OrganizationOrgIdClustersRoute: typeof OrganizationOrgIdClustersRoute
  OrganizationOrgIdOverviewRoute: typeof OrganizationOrgIdOverviewRoute
  OrganizationOrgIdSecurityRoute: typeof OrganizationOrgIdSecurityRoute
  OrganizationOrgIdSettingsRoute: typeof OrganizationOrgIdSettingsRoute
  OrganizationOrgIdIndexRoute: typeof OrganizationOrgIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/auth0-callback': {
      id: '/login/auth0-callback'
      path: '/login/auth0-callback'
      fullPath: '/login/auth0-callback'
      preLoaderRoute: typeof LoginAuth0CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/organization/$orgId/': {
      id: '/organization/$orgId/'
      path: '/organization/$orgId'
      fullPath: '/organization/$orgId'
      preLoaderRoute: typeof OrganizationOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organization/': {
      id: '/_authenticated/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AuthenticatedOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/organization/$orgId/settings': {
      id: '/organization/$orgId/settings'
      path: '/organization/$orgId/settings'
      fullPath: '/organization/$orgId/settings'
      preLoaderRoute: typeof OrganizationOrgIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$orgId/security': {
      id: '/organization/$orgId/security'
      path: '/organization/$orgId/security'
      fullPath: '/organization/$orgId/security'
      preLoaderRoute: typeof OrganizationOrgIdSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$orgId/overview': {
      id: '/organization/$orgId/overview'
      path: '/organization/$orgId/overview'
      fullPath: '/organization/$orgId/overview'
      preLoaderRoute: typeof OrganizationOrgIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$orgId/clusters': {
      id: '/organization/$orgId/clusters'
      path: '/organization/$orgId/clusters'
      fullPath: '/organization/$orgId/clusters'
      preLoaderRoute: typeof OrganizationOrgIdClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$orgId/alerts': {
      id: '/organization/$orgId/alerts'
      path: '/organization/$orgId/alerts'
      fullPath: '/organization/$orgId/alerts'
      preLoaderRoute: typeof OrganizationOrgIdAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organization/$organizationId/': {
      id: '/_authenticated/organization/$organizationId/'
      path: '/$organizationId'
      fullPath: '/organization/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/settings': {
      id: '/_authenticated/organization/$organizationId/settings'
      path: '/$organizationId/settings'
      fullPath: '/organization/$organizationId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdSettingsRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/security': {
      id: '/_authenticated/organization/$organizationId/security'
      path: '/$organizationId/security'
      fullPath: '/organization/$organizationId/security'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdSecurityRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/overview': {
      id: '/_authenticated/organization/$organizationId/overview'
      path: '/$organizationId/overview'
      fullPath: '/organization/$organizationId/overview'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdOverviewRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/clusters': {
      id: '/_authenticated/organization/$organizationId/clusters'
      path: '/$organizationId/clusters'
      fullPath: '/organization/$organizationId/clusters'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClustersRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/alerts': {
      id: '/_authenticated/organization/$organizationId/alerts'
      path: '/$organizationId/alerts'
      fullPath: '/organization/$organizationId/alerts'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdAlertsRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/$clusterId/': {
      id: '/_authenticated/organization/$organizationId/$clusterId/'
      path: '/$organizationId/$clusterId'
      fullPath: '/organization/$organizationId/$clusterId'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
    '/_authenticated/organization/$organizationId/cluster/$clusterId/overview': {
      id: '/_authenticated/organization/$organizationId/cluster/$clusterId/overview'
      path: '/$organizationId/cluster/$clusterId/overview'
      fullPath: '/organization/$organizationId/cluster/$clusterId/overview'
      preLoaderRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRouteImport
      parentRoute: typeof AuthenticatedOrganizationRouteRoute
    }
  }
}

interface AuthenticatedOrganizationRouteRouteChildren {
  AuthenticatedOrganizationIndexRoute: typeof AuthenticatedOrganizationIndexRoute
  AuthenticatedOrganizationOrganizationIdAlertsRoute: typeof AuthenticatedOrganizationOrganizationIdAlertsRoute
  AuthenticatedOrganizationOrganizationIdClustersRoute: typeof AuthenticatedOrganizationOrganizationIdClustersRoute
  AuthenticatedOrganizationOrganizationIdOverviewRoute: typeof AuthenticatedOrganizationOrganizationIdOverviewRoute
  AuthenticatedOrganizationOrganizationIdSecurityRoute: typeof AuthenticatedOrganizationOrganizationIdSecurityRoute
  AuthenticatedOrganizationOrganizationIdSettingsRoute: typeof AuthenticatedOrganizationOrganizationIdSettingsRoute
  AuthenticatedOrganizationOrganizationIdIndexRoute: typeof AuthenticatedOrganizationOrganizationIdIndexRoute
  AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute: typeof AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute
  AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute: typeof AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute
}

const AuthenticatedOrganizationRouteRouteChildren: AuthenticatedOrganizationRouteRouteChildren = {
  AuthenticatedOrganizationIndexRoute: AuthenticatedOrganizationIndexRoute,
  AuthenticatedOrganizationOrganizationIdAlertsRoute: AuthenticatedOrganizationOrganizationIdAlertsRoute,
  AuthenticatedOrganizationOrganizationIdClustersRoute: AuthenticatedOrganizationOrganizationIdClustersRoute,
  AuthenticatedOrganizationOrganizationIdOverviewRoute: AuthenticatedOrganizationOrganizationIdOverviewRoute,
  AuthenticatedOrganizationOrganizationIdSecurityRoute: AuthenticatedOrganizationOrganizationIdSecurityRoute,
  AuthenticatedOrganizationOrganizationIdSettingsRoute: AuthenticatedOrganizationOrganizationIdSettingsRoute,
  AuthenticatedOrganizationOrganizationIdIndexRoute: AuthenticatedOrganizationOrganizationIdIndexRoute,
  AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute:
    AuthenticatedOrganizationOrganizationIdClusterIdIndexRoute,
  AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute:
    AuthenticatedOrganizationOrganizationIdClusterClusterIdOverviewRoute,
}

const AuthenticatedOrganizationRouteRouteWithChildren = AuthenticatedOrganizationRouteRoute._addFileChildren(
  AuthenticatedOrganizationRouteRouteChildren
)

interface AuthenticatedRouteChildren {
  AuthenticatedOrganizationRouteRoute: typeof AuthenticatedOrganizationRouteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrganizationRouteRoute: AuthenticatedOrganizationRouteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginAuth0CallbackRoute: LoginAuth0CallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  OrganizationOrgIdAlertsRoute: OrganizationOrgIdAlertsRoute,
  OrganizationOrgIdClustersRoute: OrganizationOrgIdClustersRoute,
  OrganizationOrgIdOverviewRoute: OrganizationOrgIdOverviewRoute,
  OrganizationOrgIdSecurityRoute: OrganizationOrgIdSecurityRoute,
  OrganizationOrgIdSettingsRoute: OrganizationOrgIdSettingsRoute,
  OrganizationOrgIdIndexRoute: OrganizationOrgIdIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
