import { useParams } from '@tanstack/react-router'
import { Controller, type UseFormReturn } from 'react-hook-form'
import {
  Callout,
  CopyButton,
  Heading,
  Icon,
  InputSelect,
  InputText,
  Link,
  RadioGroup,
  Section,
} from '@qovery/shared/ui'
import { useTerraformAvailableVersions } from '../hooks/use-terraform-available-versions/use-terraform-available-versions'
import { type TerraformGeneralData } from '../terraform-general-data/terraform-general-data'
import { TERRAFORM_ENGINES } from '../utils/terraform-engines'

export const TerraformConfigurationSettings = ({ methods }: { methods: UseFormReturn<TerraformGeneralData> }) => {
  const { organizationId = '', projectId = '', environmentId = '', serviceId = '' } = useParams({ strict: false })
  const { data: versions = [], isLoading: isTerraformVersionLoading } = useTerraformAvailableVersions()
  const cliCommand = `qovery terraform setup-backend --terraform ${serviceId || '<SERVICE_ID>'}`
  const backend = methods.watch('backend')

  return (
    <div className="space-y-10">
      <Section className="gap-4">
        <div className="space-y-1">
          <Heading level={2}>Core configuration</Heading>
          <p className="text-sm text-neutral-subtle">Basic Terraform setup and state management settings.</p>
        </div>

        <Controller
          name="engine"
          control={methods.control}
          render={({ field }) => (
            <InputSelect
              label="Terraform Engine"
              className="capitalize"
              value={field.value}
              onChange={field.onChange}
              options={TERRAFORM_ENGINES.map((v) => ({ label: v.name, value: v.value, icon: <Icon name={v.icon} /> }))}
              hint="Select the Terraform engine to use for the service"
            />
          )}
        />

        <Controller
          name="provider_version.explicit_version"
          control={methods.control}
          render={({ field }) => {
            const versionOptions = versions
              .filter((v) => v.engine === methods.watch('engine'))
              .map((v) => ({ label: v.version, value: v.version }))

            return (
              <InputSelect
                label="Terraform version"
                value={field.value}
                isLoading={isTerraformVersionLoading}
                onChange={field.onChange}
                options={versionOptions}
                hint="Select the Terraform version to use for the service"
              />
            )
          }}
        />
      </Section>

      <Section className="gap-4">
        <Heading level={2}>Backend configuration</Heading>
        <Callout.Root color="neutral" className="p-4">
          <Callout.Text className="w-full">
            <Controller
              name="backend"
              control={methods.control}
              defaultValue={'kubernetes' in methods.getValues('backend') ? { kubernetes: {} } : { user_provided: {} }}
              render={({ field }) => (
                <RadioGroup.Root
                  className="flex flex-col gap-5"
                  defaultValue={'kubernetes' in field.value ? 'kubernetes' : 'user_provided'}
                  onValueChange={(value) =>
                    field.onChange(value === 'kubernetes' ? { kubernetes: {} } : { user_provided: {} })
                  }
                >
                  <label className="grid grid-cols-[16px_1fr] gap-3">
                    <RadioGroup.Item value="kubernetes" />
                    <div className="flex flex-col gap-1">
                      <span className="font-medium">Use backend generated by Qovery (Kubernetes)</span>
                      <ul className="list-disc pl-3 text-neutral-subtle">
                        <li>
                          Not recommended for production environments (as there won't be any backup of the state).
                        </li>
                        <li>Qovery manages the Terraform state in your cluster.</li>
                        <li>We override backend.tf at runtime; you don't need to configure a backend.</li>
                      </ul>
                    </div>
                  </label>
                  <label className="grid grid-cols-[16px_1fr] gap-3">
                    <RadioGroup.Item value="user_provided" />
                    <div className="flex flex-col gap-1">
                      <span className="font-medium">Use your own backend</span>
                      <ul className="list-disc pl-3 text-neutral-subtle">
                        <li>Qovery does not override your files.</li>
                        <li>You must configure your backend and set the required environment variables.</li>
                        <li>Credentials are provided via environment variables.</li>
                      </ul>
                    </div>
                  </label>
                </RadioGroup.Root>
              )}
            />

            {'kubernetes' in backend && (
              <div className="mt-4 flex w-full flex-col gap-2 rounded border border-neutral px-4 py-3 text-sm">
                <span className="font-medium">Access Terraform state from your local machine</span>
                <p className="text-neutral-subtle">
                  Once your service is created, you can configure and access the state of your Terraform service from
                  your local machine with the following CLI command.
                </p>
                <div className="flex items-center justify-between gap-6 rounded bg-surface-neutral-component p-3 text-neutral">
                  <span>
                    <span className="select-none">$ </span>
                    {cliCommand}
                  </span>
                  <CopyButton content={cliCommand} />
                </div>
              </div>
            )}
          </Callout.Text>
        </Callout.Root>
      </Section>

      <Section className="gap-4">
        <Heading level={2}>Execution credentials</Heading>
        <Callout.Root color="neutral" className="p-4">
          <Callout.Text>
            <Controller
              name="use_cluster_credentials"
              control={methods.control}
              defaultValue={methods.getValues('use_cluster_credentials')}
              render={({ field }) => (
                <RadioGroup.Root
                  defaultValue={field.value ? 'true' : 'false'}
                  className="flex flex-col gap-5"
                  onValueChange={(value) => field.onChange(value === 'true')}
                >
                  <label className="grid grid-cols-[16px_1fr] gap-3">
                    <RadioGroup.Item value="true" />
                    <div className="flex flex-col gap-1">
                      <span className="font-medium">Cluster credentials</span>
                      <span className="text-sm text-neutral-subtle">
                        Use the cluster credentials to execute this Terraform manifest.
                      </span>
                    </div>
                  </label>
                  <label className="grid grid-cols-[16px_1fr] gap-3">
                    <RadioGroup.Item value="false" />
                    <div className="flex flex-col gap-1">
                      <span className="font-medium">Environment variables</span>
                      <span className="text-sm text-neutral-subtle">
                        Use custom credentials injected as environment variables. To be used if cluster credential
                        permissions are not enough.
                      </span>
                    </div>
                  </label>
                </RadioGroup.Root>
              )}
            />

            {methods.watch('use_cluster_credentials') === false && (
              <Callout.Root color="sky" className="mt-4">
                <Callout.Icon>
                  <Icon iconName="info-circle" iconStyle="regular" />
                </Callout.Icon>
                <Callout.Text>
                  <span>
                    You will be able to define environment variables in{' '}
                    <Link
                      to="/organization/$organizationId/project/$projectId/environment/$environmentId/service/$serviceId/variables"
                      params={{ organizationId, projectId, environmentId, serviceId }}
                    >
                      the variables section
                    </Link>{' '}
                    after creating the service.
                  </span>
                </Callout.Text>
              </Callout.Root>
            )}
          </Callout.Text>
        </Callout.Root>
      </Section>

      <Section className="gap-4">
        <Heading level={2}>Execution settings</Heading>
        <Controller
          name="timeout_sec"
          control={methods.control}
          defaultValue={methods.getValues('timeout_sec')}
          rules={{
            required: true,
            validate: (value) =>
              value !== '' && !isNaN(Number(value)) && Number(value) > 0 ? true : 'Timeout must be a positive number',
          }}
          render={({ field, fieldState: { error } }) => (
            <InputText
              name={field.name}
              type="number"
              onChange={field.onChange}
              value={field.value}
              label="Execution timeout (in seconds)"
              error={error?.message}
              hint="Maximum duration for Terraform operations"
            />
          )}
        />
      </Section>
    </div>
  )
}
