import { createQueryKeys } from '@lukemorales/query-key-factory'
import axios from 'axios'
import { isHttpStatus } from '../http/is-http-status'

export interface ClusterOperatorBootstrapResponse {
  chartRepository: string
  chartName: string
  chartVersion: string
  namespace: string
  releaseName: string
  values: Record<string, unknown>
  valuesYaml: string
  helmCommand: string
}

interface ClusterOperatorBootstrapApiResponse {
  chart_repository: string
  chart_name: string
  chart_version: string
  namespace: string
  release_name: string
  values: Record<string, unknown>
  values_yaml: string
  helm_command: string
}

export interface ClusterOperatorStatusResponse {
  organizationId: string
  clusterId: string
  operatorConnected: boolean
  lastHeartbeat?: string | null
  operatorVersion?: string | null
  controllerVersion?: string | null
  requestSchemaVersion?: string | null
}

interface ClusterOperatorStatusApiResponse {
  organization_id: string
  cluster_id: string
  operator_connected: boolean
  last_heartbeat?: string | null
  operator_version?: string | null
  controller_version?: string | null
  request_schema_version?: string | null
}

function toClusterOperatorBootstrapResponse(
  response: ClusterOperatorBootstrapApiResponse
): ClusterOperatorBootstrapResponse {
  return {
    chartRepository: response.chart_repository,
    chartName: response.chart_name,
    chartVersion: response.chart_version,
    namespace: response.namespace,
    releaseName: response.release_name,
    values: response.values,
    valuesYaml: response.values_yaml,
    helmCommand: response.helm_command,
  }
}

function toClusterOperatorStatusResponse(response: ClusterOperatorStatusApiResponse): ClusterOperatorStatusResponse {
  return {
    organizationId: response.organization_id,
    clusterId: response.cluster_id,
    operatorConnected: response.operator_connected,
    lastHeartbeat: response.last_heartbeat,
    operatorVersion: response.operator_version,
    controllerVersion: response.controller_version,
    requestSchemaVersion: response.request_schema_version,
  }
}

// These endpoints are not generated by qovery-typescript-axios yet. Keeping the raw
// calls behind this data-access module avoids leaking their transport details into UI code.
export const clusterOperator = createQueryKeys('clusterOperator', {
  status: ({ organizationId, clusterId }: { organizationId: string; clusterId: string }) => ({
    queryKey: [organizationId, clusterId],
    async queryFn() {
      try {
        const response = await axios.get<ClusterOperatorStatusApiResponse>(
          `/organization/${organizationId}/cluster/${clusterId}/operator/status`
        )
        return toClusterOperatorStatusResponse(response.data)
      } catch (error) {
        if (isHttpStatus(error, 404)) return null
        throw error
      }
    },
  }),
  bootstrap: ({ organizationId, clusterId }: { organizationId: string; clusterId: string }) => ({
    queryKey: [organizationId, clusterId],
    async queryFn() {
      const response = await axios.get<ClusterOperatorBootstrapApiResponse>(
        `/organization/${organizationId}/cluster/${clusterId}/operator/bootstrap`
      )
      return toClusterOperatorBootstrapResponse(response.data)
    },
  }),
})

export const clusterOperatorMutations = {
  async attach({ organizationId, clusterId }: { organizationId: string; clusterId: string }) {
    await axios.post(`/organization/${organizationId}/cluster/${clusterId}/operator/attach`)
  },
}
