export const QOVERY_FORUM_URL = 'https://discuss.qovery.com'
export const QOVERY_STATUS_URL = 'https://status.qovery.com'
export const QOVERY_DOCS_URL = 'https://hub.qovery.com'
export const QOVERY_FEEDBACK_URL = 'https://roadmap.qovery.com'
export const QOVERY_ROADMAP_URL = 'https://roadmap.qovery.com/roadmap'
