import { useQuery } from '@tanstack/react-query'
import { MINTLIFY_API_KEY } from '@qovery/shared/util-node-env'

export interface SearchDocumentationResult {
  content?: string
  path: string
  metadata?: {
    title?: string
    description?: string | null
    deprecated?: boolean | null
    version?: string | null
    openapi?: string
    href?: string
    autogeneratedByOpenApi?: boolean
    [key: string]: unknown
  }
}

async function searchDocumentation(query: string): Promise<SearchDocumentationResult[]> {
  if (!MINTLIFY_API_KEY) {
    throw new Error('Mintlify configuration missing')
  }

  const response = await fetch('https://api.mintlify.com/discovery/v1/search/qovery', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${MINTLIFY_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query,
      pageSize: 10,
    }),
  })

  if (!response.ok) {
    throw new Error(`Search failed: ${response.statusText}`)
  }

  return response.json()
}

export function useSearchDocumentation(query: string) {
  return useQuery({
    queryKey: ['search-documentation', query],
    queryFn: () => searchDocumentation(query),
    enabled: !!query.trim(),
    staleTime: 5 * 60 * 1000, // 5 minutes
  })
}

export default useSearchDocumentation
