import { useCallback, useState } from 'react'
import { MINTLIFY_API_KEY, MINTLIFY_DOMAIN } from '@qovery/shared/util-node-env'

export interface MintlifySearchResult {
  content?: string
  path: string
  metadata?: {
    title?: string
    description?: string | null
    deprecated?: boolean | null
    version?: string | null
    openapi?: string
    href?: string
    autogeneratedByOpenApi?: boolean
    [key: string]: unknown
  }
}

export interface SearchState {
  query: string
  results: MintlifySearchResult[]
  isLoading: boolean
  error: string | null
}

export function useMintlifySearch() {
  const [state, setState] = useState<SearchState>({
    query: '',
    results: [],
    isLoading: false,
    error: null,
  })

  const search = useCallback(async (query: string) => {
    if (!query.trim()) {
      setState({ query: '', results: [], isLoading: false, error: null })
      return
    }

    if (!MINTLIFY_DOMAIN || !MINTLIFY_API_KEY) {
      setState({
        query,
        results: [],
        isLoading: false,
        error: 'Mintlify configuration missing',
      })
      return
    }

    setState((prev) => ({ ...prev, query, isLoading: true, error: null }))

    try {
      const response = await fetch(`https://api.mintlify.com/discovery/v1/search/${MINTLIFY_DOMAIN}`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${MINTLIFY_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          query,
          pageSize: 10,
        }),
      })

      if (!response.ok) {
        throw new Error(`Search failed: ${response.statusText}`)
      }

      const results: MintlifySearchResult[] = await response.json()

      setState({
        query,
        results,
        isLoading: false,
        error: null,
      })
    } catch (error) {
      setState({
        query,
        results: [],
        isLoading: false,
        error: error instanceof Error ? error.message : 'Search failed',
      })
    }
  }, [])

  return {
    ...state,
    search,
  }
}

export default useMintlifySearch
