import { useQuery } from '@tanstack/react-query'
import { MINTLIFY_API_KEY, MINTLIFY_DOMAIN } from '@qovery/shared/util-node-env'

export interface SearchDocumentationResult {
  content?: string
  path: string
  metadata?: {
    title?: string
    description?: string | null
    deprecated?: boolean | null
    version?: string | null
    openapi?: string
    href?: string
    autogeneratedByOpenApi?: boolean
    [key: string]: unknown
  }
}

async function searchDocumentation(query: string): Promise<SearchDocumentationResult[]> {
  if (!MINTLIFY_DOMAIN || !MINTLIFY_API_KEY) {
    throw new Error('Mintlify configuration missing')
  }

  const response = await fetch(`https://api.mintlify.com/discovery/v1/search/${MINTLIFY_DOMAIN}`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${MINTLIFY_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query,
      pageSize: 10,
    }),
  })

  if (!response.ok) {
    throw new Error(`Search failed: ${response.statusText}`)
  }

  return response.json()
}

export function useSearchDocumentation(query: string) {
  const enabled = !!query.trim() && !!MINTLIFY_DOMAIN && !!MINTLIFY_API_KEY

  // Temporary debug logging
  if (query.trim()) {
    console.log('[Search Debug]', {
      query,
      enabled,
      hasDomain: !!MINTLIFY_DOMAIN,
      hasApiKey: !!MINTLIFY_API_KEY,
    })
  }

  return useQuery({
    queryKey: ['search-documentation', query],
    queryFn: () => {
      console.log('[Search] Executing query for:', query)
      return searchDocumentation(query)
    },
    enabled,
    staleTime: 5 * 60 * 1000, // 5 minutes
  })
}

export default useSearchDocumentation
