export const ONBOARDING_URL = '/onboarding'
export const ONBOARDING_PERSONALIZE_URL = '/personalize'
export const ONBOARDING_MORE_URL = '/more'
export const ONBOARDING_PRICING_URL = '/pricing'
export const ONBOARDING_PROJECT_URL = '/project'
export const ONBOARDING_THANKS_URL = '/thanks'
