- name: Coveralls
  uses: coverallsapp/github-action@master
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    flag-name: Client
    path-to-lcov: ./client/coverage/lcov.info
    parallel: true
    base-path: ./client
